/* This file is automatically generated.  Changes made here will be lost! */
#define N_MCE_PHYS 258
#define N_MCE_SYS  2
#define N_MCE_VIRT 27
#define N_EXP_CFG  2033
#define N_EXP_OFF  4337
#define N_MCE_STAT 6370

#define FIRST_AC_PARAM 243
#define  LAST_AC_PARAM 257
#define FIRST_RC2_PARAM 108
#define  LAST_RC2_PARAM 177
#define FIRST_CC_PARAM 0
#define  LAST_CC_PARAM 37
#define FIRST_BC2_PARAM 194
#define  LAST_BC2_PARAM 242
#define FIRST_BC1_PARAM 178
#define  LAST_BC1_PARAM 193
#define FIRST_RC1_PARAM 38
#define  LAST_RC1_PARAM 107
