#!/bin/bash

# Replicate /data0/mas on all the other drives
touch /data/.master
for d in `seq 0 3`; do 
  if [ -d /data$d/mas ]; then
    if [ -e /data$d/.master ]; then
      rm -f /data$d/.master
    else
      rsync -avP --delete-during /data/mas /data$d
    fi
  else 
    echo "WARNING: can't find directory /data$d/mas"
  fi
done
