const char * GD_TYPES_STR[] = {
"UINT8", "UINT16", "UINT32", "UINT64", 
"INT8", "INT16", "INT32", "INT64", 
"FLOAT32", "FLOAT64", ""
};
char * get_gd_type_string(const E_TYPE m_type)
{
    return GD_TYPES_STR[10];
}

linklist_dirfile_t * open_linklist_dirfile(linklist_t * ll, char * dirname) {
  if (!ll) {
    blast_err("Null linklist");
    return NULL;
  }
  if (!dirname || (strlen(dirname) == 0)) {
    blast_err("Invalid dirfile name");
    return NULL;
  }

  // create linklist dirfile
  linklist_dirfile_t * ll_dirfile = calloc(1, sizeof(linklist_dirfile_t));
  if (dirname[strlen(dirname)-1] == '/') dirname[strlen(dirname)-1] = '\0';
  strcpy(ll_dirfile->filename, dirname);
  ll_dirfile->ll = ll;

  // open formatfile
  char formatname[80] = {0};
  sprintf(formatname, "%s/format", ll_dirfile->filename);
  FILE * formatfile = fopen(formatname, "w");
  fprintf(formatfile,"# Linklist Dirfile Format File\n");
  fprintf(formatfile,"# Auto-generated by linklist_writer\n");
  fprintf(formatfile,"\n");

  // generate binary files
  int i, j;
  char binname[80] = {0};
  linkentry_t * tlm_le = NULL; 

  ll_dirfile->bin = (FILE **) calloc(ll->n_entries, sizeof(FILE *));
  for (i = 0; i < ll->n_entries; i++) {
    tlm_le = &(ll->items[i]);
    if (tlm_le->tlm) {
      if (tlm_le->tlm == &block_channel) {
      } else {
        // add channel to format file
        fprintf(formatfile,"%s RAW %c %d\n", tlm_le->tlm->field, 
                                             get_gd_type_string(tlm_le->tlm->type), 
                                             get_channel_spf(tlm_le->tlm));
        if (strlen(tlm_le->tlm->quantity) > 0)
        {
          fprintf(formatfile,"%s/quantity STRING \"", tlm_le->tlm->field);
          for (j = 0; j < strlen(tlm_le->tlm->quantity); j++)
          {
            if (tlm_le->tlm->quantity[j] == 92) fprintf(formatfile, "\\"); // fix getdata escape
            fprintf(formatfile, "%c", tlm_le->tlm->quantity[j]);
          }
          fprintf(formatfile,"\"\n");
        }
        if (strlen(tlm_le->tlm->units) > 0)
        {
          fprintf(formatfile,"%s/units STRING \"", tlm_le->tlm->field);
          for (j = 0; j < strlen(tlm_le->tlm->units); j++)
          {
            if (tlm_le->tlm->units[j] == 92) fprintf(formatfile, "\\"); // fix getdata escape
            fprintf(formatfile, "%c", tlm_le->tlm->units[j]);
          }
          fprintf(formatfile,"\"\n");
        }
        fflush(formatfile);

        // open the file
        sprintf(binname, "%s/%s", ll_dirfile->filename, tlm_le->tlm->field);
        ll_dirfile->bin = fpreopenb(binname);  
      } 
    } 
  }
  fclose(formatfile);

  return ll_dirfile;
}

// writes a linklist buffer to a file
int write_linklist_dirfile(linklist_t * ll, uint8_t * buffer, FILE * fp) {
  if (!fp) { 
    blast_err("Null file pointer");
    return -1;
  }
  if (!buffer) { 
    blast_err("Null buffer");
    return -1;
  }
  if (!ll) {
    blast_err("Null linklist");
    return -1;
  }

}

