include ../Makefile.config

all: 

install:
	install -d -m 777 $(ETC_DIR)
	install -m 666 *.txt $(ETC_DIR)
	install -m 666 *.lut $(ETC_DIR)
	install -m 666 *.dat $(ETC_DIR)
	install -m 666 *.COF $(ETC_DIR)
	install -m 666 ephem.2000 $(ETC_DIR)

clean:
