.TH defile 1 "10 July 2004" "version 2.1" "BLAST UTILITIES"
.SH NAME
defile \(em convert a MCP written framefile into a dirfile
.SH SYNOPSIS
.nh
.B defile 
.RB [\~ \-C
.IR "name " |
.BI \-\-curfile\-name= name
|
.BR "\-c " |
.BR \-\-curfile\~ ]
.RB [\~ "\-F " |
.BR \-\-framefile\~ ]
.RB [\~ "\-R " |
.BR "\-\-resume " |
.BR "\-f " |
.BR \-\-force\~ ]
.RB [\~ \-S
.IR "name " |
.BI \-\-spec\-file= name
]
.RB [\~ \-o
.IR "dirfile " |
.BI \-\-output\-dirfile= dirfile
]
.RB [\~ "\-p " |
.BR \-\-persistent\~ ]
.RB [\~ "\-r " |
.BR "\-\-remounted\-source " |
.BI \-\-remounted\-using= path
]
.RB [\~ \-s
.IR "size " |
.BI \-\-suffix\-size= size
]
.RB [\~ \-\-help\~ ]
.RB [\~ \-\-version\~ ]
.RB [\~ \-\-\~ ]
.I "source"
.RI [\~ directory\~ ]
.hy

.SH DESCRIPTION
.B defile
converts a framefile created by
.B mcp
into a readable dirfile.
.I source
is typically the name of the first chunk of the framefile to convert.
However, if given the name of a curfile for
.IR source ,
.B defile
will use that as an indirect pointer to the framefile.
.PP
Unless you override it with the
.B -o
option, the output dirfile will have the same name as the input framefile, and
be placed in
.IR directory ,
if specified, or else in the default location, typically
.BR /data/rawdir ,
but see 
.BR "COMPILE TIME DEFAULTS" .
.PP
.B defile
can convert both finished framefiles and ones which are still being written
to by
.BR mcp .
For notes on running
.B defile
on framefiles which are still being written to, see the
.B PERSISTENT MODE
section.
.PP
In order to properly parse the datastream,
.B defile
requires a channel specification file.  By default,
.B defile
gets this from the
.I .spec
file generated by
.BR mcp .
This can be overridden with the
.B -S
option.

.SH OPTIONS
.PP
.BI "\-C " name
or
.BI \-\-curfile\-name= name
.RS
Same as (and implies)
.BR \-c ,
but use
.I name
for the name of the curfile instead of the default.
.RE
.TP
.BR "\-F " "or " \-\-framefile
Always assume
.I source
is a framefile, even when it looks like a curfile.
.TP
.BR "\-R " "or " \-\-resume
Resume an interrupted defiling.
.PP
.BI "\-S " name
or
.BI \-\-spec\-file= name
.RS
Use
.I name
as the channel specification file instead of the default.
.RE
.TP
.BR "\-c " "or " \-\-curfile
Write a curfile pointing to the output dirfile.  The default curfile name is
generally
.BR /data/etc/defile.cur ,
but see
.BR "COMPILE TIME DEFAULTS" .
To use a different name for the curfile, see the
.B \-C
option.
.TP
.BR "\-f " "or " \-\-force
Overwrite an existing dirfile.  Normally
.B defile
will complain and exit if it finds that the destination dirfile directory
already exists.  Be careful using this option:  before starting the write
.B defile
will delete the current contents of the destination directory.
.PP
.BI "\-o " dirfile
or
.BI \-\-output\-dirfile= dirfile
.RS
Call the output dirfile
.I dirfile
instead of naming it after the input framefile.
.I dirfile
can be a path relative to
.I directory
(or the default path if no
.I directory
is given), or it can be an absolute path, in which case
.I directory
is ignored.
.RE
.TP
.BR "\-p " "or " \-\-persistent
Upon reaching the end of the framefile, don't exit but wait for more data to
be added to the file.  For use when reading a framefile that is concurrently
being written to by
.BR mcp .
See
.B PERSISTENT MODE
for more information.
.TP
.BR "\-r " "or " \-\-remounted\-source
If
.I source
is a curfile, assume that the file it refers to has been mounted in a different
location than the path given in the curfile.  By default
.B defile
will typically look for the framefile in the directory
.B ../rawdir
relative to the location of the
.I source
curfile, but see
.BR "COMPILE TIME DEFAULTS" .
If you want to specify a different remounted location for the framefile, see the
.B \-\-remounted\-using
option.  This option does nothing if
.I source
is not a curfile.
.TP
.BI \-\-remounted\-using= path
Same as (and implies)
.BR \-r ,
but use
.I path
as the location for the framefile.
.I path
may be either an absolute path or a path relative to the location of the
.I source
curfile.
.PP
.BI "\-s " size
or
.BI \-\-suffix\-size= size
.RS
Assume that the suffix of the framefile (the portion of the filename which is
incremented as a hexadecimal number) is no larger than
.I size
characters.  This option only is useful if the character immediately preceding
the suffix is a hexadecimal digit and you expect the suffix will overflow.
.RE
.TP
.B \-\-help
Show the usage summary and exit.
.TP
.B \-\-version
Show the version information and exit.
.TP
.B \-\-
Indicates that everything following the
.B \-\-
is an argument, even if it begins with a
.BR \- .

.SH "PERSISTENT MODE"
When running in persistent mode (with the
.B \-p
switch),
.B defile
will periodically check for additional data in the framefile.  If the
.I source
was a curfile, it will also refer back to this to see if it has changed as well.
If the curfile has changed, it will start reading the new framefile it points
to.  If the name for the output dirfile was not explicitly set using the
.B -o
option, 
.B defile
will also start writing a new dirfile with a corresponding name.

.SH "COMPILE TIME DEFAULTS"
The following defaults may be changed at compile time from their typical values:
.IP \(bu
default curfile name: 
.B /data/etc/defile.cur
.IP \(bu
default remount path:
.B ../rawdir
.IP \(bu
default output path:
.B /data/rawdir
.PP
If they have been changed by your system administrator, this man page may not
reflect reality.  To see the actual values of these defaults, use
.BR "defile --help " .
.SH AUTHOR
D. V. Wiebe (dwiebe@physics.utoronto.ca)
