#! /bin/sh
# a little shell script to find free loop back fields
# ./check_loops LOOP0 finds free fields in LOOP0
# it only lookes for write fields.

cat tx_struct.c | grep $1 | grep \'r\'  | awk -F "," '($1!~"//")&&($1~"{"){print $4, $7, $1}' | awk '($2~"u")||($2~"s"){printf "%2d %s %s\n", $1,$2,$3}($2~"U")||($2~"S"){printf "%2d %s %s\n%2d\n",$1, $2, $3, $1+1}' | sort -n 

echo "------------------------------"
cat tx_struct.c | grep $1 | grep \'r\'  | awk -F "," '($1!~"//")&&($1~"{"){print $4, $7, $1}' | awk '($2~"u")||($2~"s"){printf "%2d %s %s\n", $1,$2,$3}($2~"U")||($2~"S"){printf "%2d %s %s\n%2d\n",$1, $2, $3, $1+1}'| sort -n | awk 'BEGIN{i=-1}{print i, i=$1}'| awk '($1<$2-2){printf "%d to %d are free\n",  $1+1, $2-1}($1==$2-2){printf "%d is free\n",  $1+1}($1==$2){printf "%d is used twice ***\n",  $1}END{printf "%d to 63 are free\n", $2+1}'

