/* This file is automatically generated.  Changes made here will be lost! */
#define N_MCE_PHYS 276
#define N_MCE_SYS  2
#define N_MCE_VIRT 28
#define N_EXP_CFG  2180
#define N_EXP_OFF  4787
#define N_MCE_STAT 6967

#define FIRST_AC_PARAM 261
#define  LAST_AC_PARAM 275
#define FIRST_RC2_PARAM 117
#define  LAST_RC2_PARAM 195
#define FIRST_CC_PARAM 0
#define  LAST_CC_PARAM 37
#define FIRST_BC2_PARAM 212
#define  LAST_BC2_PARAM 260
#define FIRST_BC1_PARAM 196
#define  LAST_BC1_PARAM 211
#define FIRST_RC1_PARAM 38
#define  LAST_RC1_PARAM 116

#define FIRST_SQ2_MAP 0
#define  LAST_SQ2_MAP 18
#define FIRST_SA_MAP 23
#define  LAST_SA_MAP 25
#define FIRST_SQ1_MAP 19
#define  LAST_SQ1_MAP 22
#define FIRST_HEATER_MAP 27
#define  LAST_HEATER_MAP 27
#define FIRST_TES_MAP 26
#define  LAST_TES_MAP 26
