#! /bin/csh
/usr/local/bin/mcp b >>& /data/rawdir/mcp.log
sleep 1
/usr/local/bin/mcp b >>& /data/rawdir/mcp.log
sleep 1
/usr/local/bin/mcp b >>& /data/rawdir/mcp.log
sleep 1
/usr/local/bin/mcp b >>& /data/rawdir/mcp.log
sleep 1
/usr/local/bin/mcp b >>& /data/rawdir/mcp.log
sleep 1
/usr/local/bin/mcp b >>& /data/rawdir/mcp.log
sleep 1
/usr/local/bin/mcp b >>& /data/rawdir/mcp.log
sleep 1
/usr/local/bin/mcp b >>& /data/rawdir/mcp.log
sleep 1
/usr/local/bin/mcp b >>& /data/rawdir/mcp.log
sleep 1
/usr/local/bin/mcp b >>& /data/rawdir/mcp.log
sleep 1
/usr/local/bin/mcp b >>& /data/rawdir/mcp.log
sleep 1
/usr/local/bin/mcp b >>& /data/rawdir/mcp.log
sleep 1
/usr/local/bin/mcp b >>& /data/rawdir/mcp.log
sleep 1
/usr/local/bin/mcp b >>& /data/rawdir/mcp.log
sleep 1
/usr/local/bin/mcp b >>& /data/rawdir/mcp.log
sleep 1
/usr/local/bin/mcp b >>& /data/rawdir/mcp.log
sleep 1
/usr/local/bin/mcp b >>& /data/rawdir/mcp.log
sleep 1
/usr/local/bin/mcp b >>& /data/rawdir/mcp.log
/sbin/reboot

