current_ntones_roach1
current_ntones_roach2
current_ntones_roach3
current_ntones_roach4
current_ntones_roach5

prev_nkids_found_roach2
prev_nkids_found_roach2
prev_nkids_found_roach3
prev_nkids_found_roach4
prev_nkids_found_roach5

pow_per_tone_roach1
pow_per_tone_roach2
pow_per_tone_roach3
pow_per_tone_roach4
pow_per_tone_roach5

read_atten_out_roach1
read_atten_out_roach2
read_atten_out_roach3
read_atten_out_roach4
read_atten_out_roach5

read_atten_out_roach1
read_atten_out_roach2
read_atten_out_roach3
read_atten_out_roach4
read_atten_out_roach5

status_roach1 int32
status_roach2 int32
status_roach3 int32
status_roach4 int32
status_roach5 int32

state_roach1
state_roach2
state_roach3
state_roach4
state_roach5

median_df_roach1
median_df_roach2
median_df_roach3
median_df_roach4
median_df_roach5

thermistor_66
thermistor_64
thermistor_69
thermistor_72

pps_count_roach1
pps_count_roach2
pps_count_roach3
pps_count_roach4
pps_count_roach5

pi_error_count_roach1
pi_error_count_roach2
pi_error_count_roach3
pi_error_count_roach4
pi_error_count_roach5

targ_sweep_span_roach1
targ_sweep_span_roach2
targ_sweep_span_roach3
targ_sweep_span_roach4
targ_sweep_span_roach5

trnd_sweep_span_roach1
trnd_sweep_span_roach2
trnd_sweep_span_roach3
trnd_sweep_span_roach4
trnd_sweep_span_roach5
