# Timestreams for noise PSD
# No downsampling or compression specified

lo_freq_read_roach1
lo_freq_req_roach1
status_roach1
current_ntones_roach1
nkids_found_roach1
pow_per_tone_roach1
set_atten_out_roach1
read_atten_out_roach1
set_atten_in_roach1
read_atten_in_roach1
adcI_rms_roach1
adcQ_rms_roach1
lo_center_freq_roach1
lo_freq_read_roach1
df_retune_thresh_roach1
nflag_thresh_roach1 
nkids_bad_roach1
state_roach1
lo_freq_read_roach2
lo_freq_req_roach2
status_roach2
current_ntones_roach2
nkids_found_roach2
pow_per_tone_roach2
set_atten_out_roach2
read_atten_out_roach2
set_atten_in_roach2
read_atten_in_roach2
adcI_rms_roach2
adcQ_rms_roach2
lo_center_freq_roach2
lo_freq_read_roach2
df_retune_thresh_roach2
nflag_thresh_roach2 
nkids_bad_roach2
state_roach2
lo_freq_read_roach3
lo_freq_req_roach3
status_roach3
current_ntones_roach3
nkids_found_roach3
pow_per_tone_roach3
set_atten_out_roach3
read_atten_out_roach3
set_atten_in_roach3
read_atten_in_roach3
adcI_rms_roach3
adcQ_rms_roach3
lo_center_freq_roach3
lo_freq_read_roach3
df_retune_thresh_roach3
nflag_thresh_roach3 
nkids_bad_roach3
state_roach3
lo_freq_read_roach4
lo_freq_req_roach4
status_roach4
current_ntones_roach4
nkids_found_roach4
pow_per_tone_roach4
set_atten_out_roach4
read_atten_out_roach4
set_atten_in_roach4
read_atten_in_roach4
adcI_rms_roach4
adcQ_rms_roach4
lo_center_freq_roach4
lo_freq_read_roach4
df_retune_thresh_roach4
nflag_thresh_roach4 
nkids_bad_roach4
state_roach4
lo_freq_read_roach5
lo_freq_req_roach5
status_roach5
current_ntones_roach5
nkids_found_roach5
pow_per_tone_roach5
set_atten_out_roach5
read_atten_out_roach5
set_atten_in_roach5
read_atten_in_roach5
adcI_rms_roach5
adcQ_rms_roach5
lo_center_freq_roach5
lo_freq_read_roach5
df_retune_thresh_roach5
nflag_thresh_roach5 
nkids_bad_roach5
state_roach5
count_cmd_s
count_cmd_s
roach_fridge_cycle_warning
roach_lamp_now
pps_count_roach1
packet_count_roach1
pps_count_roach2
packet_count_roach2
pps_count_roach3
packet_count_roach3
pps_count_roach4
packet_count_roach4
pps_count_roach5
packet_count_roach5
thermistor_63
thermistor_64
thermistor_65
thermistor_66
thermistor_67
thermistor_68
thermistor_69
thermistor_70
thermistor_71
thermistor_72
kidA_roachN_index NONE 488
kidA_roachN NONE 488
kidB_roachN_index NONE 488
kidB_roachN NONE 488
kidC_roachN_index NONE 488
kidC_roachN NONE 488
kidD_roachN_index NONE 488
kidD_roachN NONE 488
kidE_roachN_index NONE 488
kidE_roachN NONE 488
kidF_roachN_index NONE 488
kidF_roachN NONE 488
kidG_roachN_index NONE 488
kidG_roachN NONE 488
kidH_roachN_index NONE 488
kidH_roachN NONE 488
kidI_roachN_index NONE 488
kidI_roachN NONE 488
kidJ_roachN_index NONE 488
kidJ_roachN NONE 488
kidK_roachN_index NONE 488
kidK_roachN NONE 488
kidL_roachN_index NONE 488
kidL_roachN NONE 488
kidM_roachN_index NONE 488
kidM_roachN NONE 488
kidN_roachN_index NONE 488
kidN_roachN NONE 488
kidO_roachN_index NONE 488
kidO_roachN NONE 488
