#
# Linklist "all_telemetry.ll" Format File
# Auto-generated by linklist
#
# Serial=3e657aeb
# Blk Size=185379
# Frames per file=900
#
LL_NO_AUTO_CHECKSUM

test_values    NONE    200
_TLM_CHECKSUM_
heater_status_write    NONE    1
heater_status_read    NONE    1
cycle_state    NONE    1
stage_chopper    NONE    200
_TLM_CHECKSUM_
read_dio    NONE    1
tr_fpa_1k    NONE    200
_TLM_CHECKSUM_
tr_250_fpa    NONE    200
_TLM_CHECKSUM_
tr_1k_plate    NONE    200
_TLM_CHECKSUM_
tr_300mk_strap    NONE    200
_TLM_CHECKSUM_
tr_350_fpa    NONE    200
_TLM_CHECKSUM_
tr_he4_pot    NONE    200
_TLM_CHECKSUM_
tr_he3_fridge    NONE    200
_TLM_CHECKSUM_
tr_500_fpa    NONE    200
_TLM_CHECKSUM_
rox_bias    NONE    1
bias_alsa_state_rox    NONE    1
n2_flow_v    NONE    1
he_blow_v    NONE    1
he_pot_hi_flow_v    NONE    1
he_pot_lo_flow_v    NONE    1
he_purge_flow_v    NONE    1
alarm_gauge    NONE    1
of_status    NONE    1
if_status    NONE    1
labjack_conn_status    NONE    1
td_charcoal_hs    NONE    200
_TLM_CHECKSUM_
td_vcs2_filt    NONE    200
_TLM_CHECKSUM_
td_250fpa    NONE    200
_TLM_CHECKSUM_
td_hwp    NONE    200
_TLM_CHECKSUM_
td_vcs1_hx    NONE    200
_TLM_CHECKSUM_
td_1k_fridge    NONE    200
_TLM_CHECKSUM_
td_4k_plate    NONE    200
_TLM_CHECKSUM_
td_vcs1_filt    NONE    200
_TLM_CHECKSUM_
td_m3    NONE    200
_TLM_CHECKSUM_
td_charcoal    NONE    200
_TLM_CHECKSUM_
td_ob_filter    NONE    200
_TLM_CHECKSUM_
td_vcs2_plate    NONE    200
_TLM_CHECKSUM_
td_m4    NONE    200
_TLM_CHECKSUM_
td_4k_filt    NONE    200
_TLM_CHECKSUM_
td_vcs2_hx    NONE    200
_TLM_CHECKSUM_
td_vcs1_plate    NONE    200
_TLM_CHECKSUM_
level_sensor_read    NONE    1
cal_lamp_read    NONE    200
_TLM_CHECKSUM_
heater_300mk_read    NONE    1
thermistor_1    NONE    1
thermistor_2    NONE    1
thermistor_3    NONE    1
thermistor_4    NONE    1
thermistor_5    NONE    1
thermistor_6    NONE    1
thermistor_7    NONE    1
thermistor_8    NONE    1
thermistor_9    NONE    1
thermistor_10    NONE    1
thermistor_11    NONE    1
thermistor_12    NONE    1
thermistor_13    NONE    1
thermistor_14    NONE    1
thermistor_15    NONE    1
thermistor_16    NONE    1
thermistor_17    NONE    1
thermistor_18    NONE    1
thermistor_19    NONE    1
thermistor_20    NONE    1
thermistor_21    NONE    1
thermistor_22    NONE    1
thermistor_23    NONE    1
thermistor_24    NONE    1
thermistor_25    NONE    1
thermistor_26    NONE    1
thermistor_27    NONE    1
thermistor_28    NONE    1
thermistor_29    NONE    1
thermistor_30    NONE    1
thermistor_31    NONE    1
thermistor_32    NONE    1
thermistor_33    NONE    1
thermistor_34    NONE    1
thermistor_35    NONE    1
thermistor_36    NONE    1
thermistor_37    NONE    1
thermistor_38    NONE    1
thermistor_39    NONE    1
thermistor_40    NONE    1
thermistor_41    NONE    1
thermistor_42    NONE    1
thermistor_43    NONE    1
thermistor_44    NONE    1
thermistor_45    NONE    1
thermistor_46    NONE    1
thermistor_47    NONE    1
thermistor_48    NONE    1
thermistor_49    NONE    1
thermistor_50    NONE    1
thermistor_51    NONE    1
thermistor_52    NONE    1
thermistor_53    NONE    1
thermistor_54    NONE    1
thermistor_55    NONE    1
thermistor_56    NONE    1
thermistor_57    NONE    1
thermistor_58    NONE    1
thermistor_59    NONE    1
thermistor_60    NONE    1
thermistor_61    NONE    1
thermistor_62    NONE    1
thermistor_63    NONE    1
thermistor_64    NONE    1
thermistor_65    NONE    1
thermistor_66    NONE    1
thermistor_67    NONE    1
thermistor_68    NONE    1
thermistor_69    NONE    1
thermistor_70    NONE    1
thermistor_71    NONE    1
thermistor_72    NONE    1
thermistor_73    NONE    1
thermistor_74    NONE    1
current_eth_switch    NONE    1
current_fc1    NONE    1
current_xsc0    NONE    1
current_fc2    NONE    1
current_xsc1    NONE    1
current_ele_mot    NONE    1
current_pivot    NONE    1
current_rw_mot    NONE    1
current_hd_pv    NONE    1
current_gyros    NONE    1
current_data_transmit    NONE    1
clin_of_x    NONE    1
clin_of_y    NONE    1
clin_if_x    NONE    1
clin_if_y    NONE    1
clin_of_t    NONE    1
clin_if_t    NONE    1
status_charcoal_heater    NONE    1
status_250_LNA    NONE    1
status_1K_heater    NONE    1
status_charcoal_hs    NONE    1
status_500_LNA    NONE    1
status_350_LNA    NONE    1
status_300mk_heater    NONE    1
status_cal_lamp    NONE    1
x0_point_az_raw    NONE    1
x0_point_az    NONE    1
x0_point_el_raw    NONE    1
_TLM_CHECKSUM_
x0_point_el    NONE    1
x0_point_sigma    NONE    1
x0_point_az_trim    NONE    1
x0_point_el_trim    NONE    1
x0_cd_robust_mode    NONE    1
x1_point_az_raw    NONE    1
x1_point_az    NONE    1
x1_point_el_raw    NONE    1
x1_point_el    NONE    1
x1_point_sigma    NONE    1
x1_point_az_trim    NONE    1
x1_point_el_trim    NONE    1
x1_cd_robust_mode    NONE    1
x1_heater    NONE    1
x0_heater    NONE    1
x0_ctr_mcp    NONE    200
_TLM_CHECKSUM_
x0_last_trig_age_cs    NONE    200
_TLM_CHECKSUM_
x0_last_trig_ctr_mcp    NONE    200
_TLM_CHECKSUM_
x0_predicted_streaking_px    NONE    200
_TLM_CHECKSUM_
x0_last_trig_ctr_stars    NONE    200
_TLM_CHECKSUM_
x0_image_blobn_x    NONE    200
_TLM_CHECKSUM_
x0_image_blobn_y    NONE    200
_TLM_CHECKSUM_
x0_image_blobn_flux    NONE    200
_TLM_CHECKSUM_
x0_image_blobn_peak_to_flux    NONE    200
_TLM_CHECKSUM_
x1_last_trig_ctr_stars    NONE    200
_TLM_CHECKSUM_
x1_image_blobn_x    NONE    200
_TLM_CHECKSUM_
x1_image_blobn_y    NONE    200
_TLM_CHECKSUM_
x1_image_blobn_flux    NONE    200
_TLM_CHECKSUM_
x1_image_blobn_peak_to_flux    NONE    200
_TLM_CHECKSUM_
x1_predicted_streaking_px    NONE    200
_TLM_CHECKSUM_
x0_last_trig_lat    NONE    200
_TLM_CHECKSUM_
x0_last_trig_lst    NONE    200
_TLM_CHECKSUM_
x0_image_num_blobs_found    NONE    1
x0_image_num_blobs_matched    NONE    1
x0_ctr_stars    NONE    200
_TLM_CHECKSUM_
x0_image_ctr_stars    NONE    200
_TLM_CHECKSUM_
x0_image_ctr_mcp    NONE    200
_TLM_CHECKSUM_
x0_hk_temp_lens    NONE    1
x0_hk_temp_comp    NONE    1
x0_hk_temp_plate    NONE    1
x0_hk_temp_flange    NONE    1
x0_hk_pressure    NONE    1
x0_hk_disk    NONE    1
x0_image_eq_valid    NONE    1
x0_cam_gain_valid    NONE    1
x0_image_hor_valid    NONE    1
x0_image_afocus_metric_valid    NONE    1
x0_stars_run_time    NONE    1
x0_cam_gain_db    NONE    1
x0_lens_focus    NONE    1
x0_lens_aperture    NONE    1
x0_image_num_exposures    NONE    1
x0_image_stats_mean    NONE    1
x0_image_stats_noise    NONE    1
x0_image_stats_gaindb    NONE    1
x0_image_stats_num_px_sat    NONE    1
x0_image_stats_frac_px_sat    NONE    1
x0_image_afocus_metric    NONE    1
x0_image_eq_iplate    NONE    1
x0_image_hor_iplate    NONE    1
x0_image_eq_ra    NONE    1
x0_image_eq_dec    NONE    1
x0_image_eq_roll    NONE    1
x0_image_eq_sigma_ra    NONE    1
x0_image_eq_sigma_dec    NONE    1
x0_image_eq_sigma_roll    NONE    1
x0_image_eq_sigma_pointing    NONE    1
x0_image_hor_az    NONE    1
x0_image_hor_el    NONE    1
x0_image_hor_roll    NONE    1
x0_image_hor_sigma_az    NONE    1
x0_image_hor_sigma_el    NONE    1
x0_image_hor_sigma_roll    NONE    1
x0_image_hor_sigma_pointing    NONE    1
x1_image_num_blobs_found    NONE    1
x1_image_num_blobs_matched    NONE    1
x1_ctr_stars    NONE    200
_TLM_CHECKSUM_
x1_image_ctr_stars    NONE    200
_TLM_CHECKSUM_
x1_image_ctr_mcp    NONE    200
_TLM_CHECKSUM_
x1_hk_temp_lens    NONE    1
x1_hk_temp_comp    NONE    1
x1_hk_temp_plate    NONE    1
x1_hk_temp_flange    NONE    1
x1_hk_pressure    NONE    1
x1_hk_disk    NONE    1
x1_image_eq_valid    NONE    1
x1_cam_gain_valid    NONE    1
x1_image_hor_valid    NONE    1
x1_image_afocus_metric_valid    NONE    1
x1_stars_run_time    NONE    1
x1_cam_gain_db    NONE    1
x1_lens_focus    NONE    1
x1_lens_aperture    NONE    1
x1_image_num_exposures    NONE    1
x1_image_stats_mean    NONE    1
x1_image_stats_noise    NONE    1
x1_image_stats_gaindb    NONE    1
x1_image_stats_num_px_sat    NONE    1
x1_image_stats_frac_px_sat    NONE    1
x1_image_afocus_metric    NONE    1
x1_image_eq_iplate    NONE    1
x1_image_hor_iplate    NONE    1
x1_image_eq_ra    NONE    1
x1_image_eq_dec    NONE    1
x1_image_eq_roll    NONE    1
x1_image_eq_sigma_ra    NONE    1
x1_image_eq_sigma_dec    NONE    1
x1_image_eq_sigma_roll    NONE    1
x1_image_eq_sigma_pointing    NONE    1
x1_image_hor_az    NONE    1
x1_image_hor_el    NONE    1
x1_image_hor_roll    NONE    1
x1_image_hor_sigma_az    NONE    1
x1_image_hor_sigma_el    NONE    1
x1_image_hor_sigma_roll    NONE    1
x1_image_hor_sigma_pointing    NONE    1
subframe_counter_1hz    NONE    100
_TLM_CHECKSUM_
subframe_counter_5hz    NONE    100
time    NONE    100
_TLM_CHECKSUM_
time_usec    NONE    100
_TLM_CHECKSUM_
time_sip    NONE    100
_TLM_CHECKSUM_
lst    NONE    100
_TLM_CHECKSUM_
parts_sched    NONE    100
_TLM_CHECKSUM_
lat    NONE    100
_TLM_CHECKSUM_
lon    NONE    100
_TLM_CHECKSUM_
ra    NONE    100
_TLM_CHECKSUM_
dec    NONE    100
_TLM_CHECKSUM_
start_cycle    NONE    100
_TLM_CHECKSUM_
lst_sched    NONE    100
_TLM_CHECKSUM_
start_set_cycle    NONE    100
_TLM_CHECKSUM_
ampl_500_bias    NONE    5
ampl_350_bias    NONE    5
ampl_250_bias    NONE    5
ampl_rox_bias    NONE    5
ampl_x_bias    NONE    5
dig21_das    NONE    5
dig65_das    NONE    5
ramp_ena_bias    NONE    5
ramp_ampl_bias    NONE    5
t_padcdc_rec    NONE    5
t_pauram_rec    NONE    5
t_hkdcdc_rec    NONE    5
vt_stbd_das    NONE    5
vt_stbd_rec    NONE    5
vt_port_das    NONE    5
vt_port_rec    NONE    5
vt_mot_pump_val    NONE    5
vt_1_prime    NONE    5
vt_if_top_back    NONE    5
vt_hwpr_mot    NONE    5
_TLM_CHECKSUM_
vt_if_top_frnt    NONE    5
vt_hwpr_feed    NONE    5
vt_if_bot_frnt    NONE    5
vt_strut_bot    NONE    5
vt_strut_side    NONE    5
vt_2_prime    NONE    5
vt_if_bot_back    NONE    5
vt_dac_box    NONE    5
t_mot_act    NONE    5
t_push_plate    NONE    5
t_1_second    NONE    5
t_2_second    NONE    5
he4_lev    NONE    5
i_charcoal    NONE    5
i_cal_lamp    NONE    5
i_hs_char    NONE    5
i_hs_pot    NONE    5
i_300mk    NONE    5
i_jfet    NONE    5
pin_in_lock    NONE    5
_TLM_CHECKSUM_
period_cal    NONE    5
status_eth    NONE    5
az_null    NONE    100
_TLM_CHECKSUM_
az_sun    NONE    5
lvdt_low_act    NONE    5
status_mcc    NONE    5
cryostate    NONE    5
upslot_sched    NONE    5
t_chip_flc    NONE    5
veto_sensor    NONE    5
i_level_on_bal    NONE    5
i_level_off_bal    NONE    5
i_el_req_avg_bal    NONE    5
status_bal    NONE    5
enc_potvalve    NONE    5
pos_potvalve    NONE    5
state_potvalve    NONE    5
vel_potvalve    NONE    5
i_open_potvalve    NONE    5
i_close_potvalve    NONE    5
i_hold_potvalve    NONE    5
thresh_clos_potvalve    NONE    5
threshlclos_potvalve    NONE    5
thresh_open_potvalve    NONE    5
_TLM_CHECKSUM_
lims_pumpvalve    NONE    5
pos_pumpvalve    NONE    5
lims_fillvalve    NONE    5
pos_fillvalve    NONE    5
vel_valves    NONE    5
i_move_valves    NONE    5
i_hold_valves    NONE    5
acc_valves    NONE    5
vel_bal    NONE    5
acc_bal    NONE    5
i_move_bal    NONE    5
i_hold_bal    NONE    5
pos_bal    NONE    5
lim_bal    NONE    5
alt_sip    NONE    5
lat_sip    NONE    5
lon_sip    NONE    5
mode_p    NONE    5
x_p    NONE    5
_TLM_CHECKSUM_
y_p    NONE    5
vel_az_p    NONE    5
del_p    NONE    5
w_p    NONE    5
offset_ifel_gy    NONE    5
offset_ifroll_gy    NONE    5
offset_ifyaw_gy    NONE    5
lvdt_high_act    NONE    5
pulse_cal    NONE    5
sigma_clin    NONE    5
mks_hi_sip    NONE    5
mks_med_sip    NONE    5
pref_tp_sf    NONE    5
bi0_fifo_size    NONE    5
plover    NONE    5
jfet_set_on    NONE    5
jfet_set_off    NONE    5
state_cycle    NONE    5
g_p_heat_gy    NONE    5
g_i_heat_gy    NONE    5
_TLM_CHECKSUM_
g_d_heat_gy    NONE    5
t_set_gy    NONE    5
h_age_gy    NONE    5
h_hist_gy    NONE    5
ra_1_p    NONE    5
dec_1_p    NONE    5
ra_2_p    NONE    5
dec_2_p    NONE    5
ra_3_p    NONE    5
dec_3_p    NONE    5
ra_4_p    NONE    5
dec_4_p    NONE    5
trim_clin    NONE    5
trim_enc    NONE    5
trim_motor_enc    NONE    5
trim_null    NONE    5
trim_mag1    NONE    5
trim_mag2    NONE    5
gain_bal    NONE    5
el_clin    NONE    5
_TLM_CHECKSUM_
h_p    NONE    5
el_lut_clin    NONE    5
mks_lo_sip    NONE    5
alt    NONE    5
mode_az_mc    NONE    5
mode_el_mc    NONE    5
dest_az_mc    NONE    5
dest_el_mc    NONE    5
vel_az_mc    NONE    5
vel_el_mc    NONE    5
dir_az_mc    NONE    5
dir_el_mc    NONE    5
slew_veto    NONE    5
sveto_len    NONE    5
pot_lock    NONE    5
dith_el    NONE    5
state_lock    NONE    5
goal_lock    NONE    5
seized_act    NONE    5
n_dith_p    NONE    5
_TLM_CHECKSUM_
x_vel_stage    NONE    5
x_stp_stage    NONE    5
x_str_stage    NONE    5
y_lim_stage    NONE    5
i_dith_el    NONE    5
y_stp_stage    NONE    5
y_str_stage    NONE    5
x_lim_stage    NONE    5
y_vel_stage    NONE    5
he4_lev_old    NONE    5
offset_ifelxsc0_gy    NONE    5
offset_ifelxsc1_gy    NONE    5
offset_ifrollxsc0_gy    NONE    5
offset_ifrollxsc1_gy    NONE    5
offset_ifyawxsc0_gy    NONE    5
offset_ifyawxsc1_gy    NONE    5
new_offset_ifelmotorenc_gy    NONE    100
_TLM_CHECKSUM_
int_ifelmotorenc    NONE    100
_TLM_CHECKSUM_
new_offset_ifyawmag1_gy    NONE    100
_TLM_CHECKSUM_
new_offset_ifrollmag1_gy    NONE    100
_TLM_CHECKSUM_
int_ifyawmag1    NONE    100
_TLM_CHECKSUM_
int_ifrollmag1    NONE    100
_TLM_CHECKSUM_
d_az_mag1    NONE    100
_TLM_CHECKSUM_
new_offset_ifyawmag2_gy    NONE    100
_TLM_CHECKSUM_
new_offset_ifrollmag2_gy    NONE    100
_TLM_CHECKSUM_
int_ifyawmag2    NONE    100
_TLM_CHECKSUM_
int_ifrollmag2    NONE    100
_TLM_CHECKSUM_
d_az_mag2    NONE    100
_TLM_CHECKSUM_
new_offset_ifelxsc0_gy    NONE    100
_TLM_CHECKSUM_
new_offset_ifyawxsc0_gy    NONE    100
_TLM_CHECKSUM_
new_offset_ifrollxsc0_gy    NONE    100
_TLM_CHECKSUM_
d_az_xsc0    NONE    100
_TLM_CHECKSUM_
int_ifrollxsc0    NONE    100
_TLM_CHECKSUM_
int_ifyawxsc0    NONE    100
_TLM_CHECKSUM_
int_ifelxsc0    NONE    100
_TLM_CHECKSUM_
prev_soln_az_xsc0    NONE    100
_TLM_CHECKSUM_
prev_soln_el_xsc0    NONE    100
_TLM_CHECKSUM_
new_offset_ifelxsc1_gy    NONE    100
_TLM_CHECKSUM_
new_offset_ifyawxsc1_gy    NONE    100
_TLM_CHECKSUM_
new_offset_ifrollxsc1_gy    NONE    100
_TLM_CHECKSUM_
d_az_xsc1    NONE    100
_TLM_CHECKSUM_
int_ifyawxsc1    NONE    100
_TLM_CHECKSUM_
int_ifrollxsc1    NONE    100
_TLM_CHECKSUM_
int_ifelxsc1    NONE    100
_TLM_CHECKSUM_
prev_soln_az_xsc1    NONE    100
_TLM_CHECKSUM_
prev_soln_el_xsc1    NONE    100
_TLM_CHECKSUM_
pos_lock    NONE    5
pos_0_act    NONE    5
pos_1_act    NONE    5
pos_2_act    NONE    5
enc_0_act    NONE    5
enc_1_act    NONE    5
enc_2_act    NONE    5
goal_sf    NONE    5
focus_sf    NONE    5
offset_ifrollmag1_gy    NONE    5
offset_ifyawmag1_gy    NONE    5
offset_ifrolldgps_gy    NONE    1
offset_ifyawdgps_gy    NONE    1
offset_ifrollmag2_gy    NONE    5
offset_ifyawmag2_gy    NONE    5
offset_ifrollpss_gy    NONE    5
offset_ifyawpss_gy    NONE    5
next_i_hwpr_p    NONE    5
next_i_dith_p    NONE    5
pref_ts_sf    NONE    5
spread_sf    NONE    5
acc_lock    NONE    5
_TLM_CHECKSUM_
i_move_act    NONE    5
i_hold_act    NONE    5
vel_act    NONE    5
acc_act    NONE    5
i_move_lock    NONE    5
i_hold_lock    NONE    5
vel_lock    NONE    5
g_prime_sf    NONE    5
g_second_sf    NONE    5
step_sf    NONE    5
wait_sf    NONE    5
mode_sf    NONE    5
correction_sf    NONE    5
age_sf    NONE    5
offset_sf    NONE    5
t_prime_sf    NONE    5
t_second_sf    NONE    5
flags_act    NONE    5
lvdt_spread_act    NONE    5
el_sun    NONE    5
_TLM_CHECKSUM_
hwpr_cal    NONE    5
mode_cal    NONE    5
overshoot_hwpr    NONE    5
drive_info_rw    NONE    5
drive_err_cts_rw    NONE    5
drive_info_el    NONE    5
drive_err_cts_el    NONE    5
drive_info_piv    NONE    5
drive_err_cts_piv    NONE    5
vel_hwpr    NONE    5
acc_hwpr    NONE    5
i_move_hwpr    NONE    5
i_hold_hwpr    NONE    5
pos_hwpr    NONE    5
enc_hwpr    NONE    5
step_start_bias    NONE    5
step_end_bias    NONE    5
_TLM_CHECKSUM_
step_n_bias    NONE    5
step_time_bias    NONE    5
step_pul_len_bias    NONE    5
step_array_bias    NONE    5
step_start_phase    NONE    5
step_end_phase    NONE    5
step_nsteps_phase    NONE    5
step_time_phase    NONE    5
step_ena_bias    NONE    5
step_ena_phase    NONE    5
v_batt_cc1    NONE    1
v_arr_cc1    NONE    1
i_batt_cc1    NONE    1
i_arr_cc1    NONE    1
t_hs_cc1    NONE    1
fault_cc1    NONE    1
alarm_cc1    NONE    1
v_targ_cc1    NONE    1
state_cc1    NONE    1
lvdt_0_act    NONE    5
lvdt_1_act    NONE    5
lvdt_2_act    NONE    5
gy_az_vel    NONE    5
gy_el_vel    NONE    5
gy_total_vel    NONE    5
_TLM_CHECKSUM_
gy_total_accel    NONE    5
offset_0_act    NONE    5
offset_1_act    NONE    5
offset_2_act    NONE    5
goal_0_act    NONE    5
goal_1_act    NONE    5
goal_2_act    NONE    5
ok_pss    NONE    5
sigma_pss    NONE    5
cal_imin_pss    NONE    5
az_raw_pss    NONE    5
el_raw_pss    NONE    5
az_pss    NONE    5
trim_pss    NONE    5
trim_dgps    NONE    5
cal_off_pss1    NONE    5
cal_off_pss2    NONE    5
cal_off_pss3    NONE    5
cal_off_pss4    NONE    5
_TLM_CHECKSUM_
cal_off_pss5    NONE    5
cal_off_pss6    NONE    5
cal_off_pss7    NONE    5
cal_off_pss8    NONE    5
cal_d_pss1    NONE    5
cal_d_pss2    NONE    5
cal_d_pss3    NONE    5
cal_d_pss4    NONE    5
cal_d_pss5    NONE    5
cal_d_pss6    NONE    5
cal_d_pss7    NONE    5
cal_d_pss8    NONE    5
snr_pss1    NONE    5
snr_pss2    NONE    5
snr_pss3    NONE    5
snr_pss4    NONE    5
snr_pss5    NONE    5
snr_pss6    NONE    5
snr_pss7    NONE    5
snr_pss8    NONE    5
_TLM_CHECKSUM_
az_raw_pss1    NONE    5
az_raw_pss2    NONE    5
az_raw_pss3    NONE    5
az_raw_pss4    NONE    5
az_raw_pss5    NONE    5
az_raw_pss6    NONE    5
az_raw_pss7    NONE    5
az_raw_pss8    NONE    5
el_raw_pss1    NONE    5
el_raw_pss2    NONE    5
el_raw_pss3    NONE    5
el_raw_pss4    NONE    5
el_raw_pss5    NONE    5
el_raw_pss6    NONE    5
el_raw_pss7    NONE    5
el_raw_pss8    NONE    5
v1_1_pss    NONE    5
v2_1_pss    NONE    5
_TLM_CHECKSUM_
v3_1_pss    NONE    5
v4_1_pss    NONE    5
v5_1_pss    NONE    5
v1_2_pss    NONE    5
v2_2_pss    NONE    5
v3_2_pss    NONE    5
v4_2_pss    NONE    5
v5_2_pss    NONE    5
v1_3_pss    NONE    5
v2_3_pss    NONE    5
_TLM_CHECKSUM_
v3_3_pss    NONE    5
v4_3_pss    NONE    5
v5_3_pss    NONE    5
v1_4_pss    NONE    5
v2_4_pss    NONE    5
v3_4_pss    NONE    5
v4_4_pss    NONE    5
v5_4_pss    NONE    5
v1_5_pss    NONE    5
v2_5_pss    NONE    5
_TLM_CHECKSUM_
v3_5_pss    NONE    5
v4_5_pss    NONE    5
v5_5_pss    NONE    5
v1_6_pss    NONE    5
v2_6_pss    NONE    5
v3_6_pss    NONE    5
v4_6_pss    NONE    5
v5_6_pss    NONE    5
v1_7_pss    NONE    5
v2_7_pss    NONE    5
_TLM_CHECKSUM_
v3_7_pss    NONE    5
v4_7_pss    NONE    5
v5_7_pss    NONE    5
v1_8_pss    NONE    5
v2_8_pss    NONE    5
v3_8_pss    NONE    5
v4_8_pss    NONE    5
v5_8_pss    NONE    5
accel_az    NONE    5
led_cc1    NONE    5
force_sbsc    NONE    5
exp_int_sbsc    NONE    5
_TLM_CHECKSUM_
exp_time_sbsc    NONE    5
foc_res_sbsc    NONE    5
move_tol_sbsc    NONE    5
maxblob_sbsc    NONE    5
grid_sbsc    NONE    5
thresh_sbsc    NONE    5
mdist_sbsc    NONE    5
mapmean_sbsc    NONE    5
mapsigma_sbsc    NONE    5
ccd_t_sbsc    NONE    5
nblobs_sbsc    NONE    5
blob00_x_sbsc    NONE    5
blob00_y_sbsc    NONE    5
blob00_f_sbsc    NONE    5
blob00_s_sbsc    NONE    5
blob01_x_sbsc    NONE    5
blob01_y_sbsc    NONE    5
blob01_f_sbsc    NONE    5
blob01_s_sbsc    NONE    5
blob02_x_sbsc    NONE    5
_TLM_CHECKSUM_
blob02_y_sbsc    NONE    5
blob02_f_sbsc    NONE    5
blob02_s_sbsc    NONE    5
g_pt_az    NONE    5
g_pt_el    NONE    5
pos0_hwpr    NONE    5
pos1_hwpr    NONE    5
pos2_hwpr    NONE    5
pos3_hwpr    NONE    5
i_pos_rq_hwpr    NONE    5
rate_highrate    NONE    1
rate_biphase    NONE    1
mpsse_clock_speed    NONE    1
rate_pilot    NONE    1
nkids_tlm_roach1    NONE    1
skids_tlm_roach1    NONE    1
nkids_tlm_roach2    NONE    1
skids_tlm_roach2    NONE    1
nkids_tlm_roach3    NONE    1
skids_tlm_roach3    NONE    1
nkids_tlm_roach4    NONE    1
skids_tlm_roach4    NONE    1
nkids_tlm_roach5    NONE    1
skids_tlm_roach5    NONE    1
roach_tlm_mode    NONE    1
read_wait_hwpr    NONE    5
_TLM_CHECKSUM_
i_pos_hwpr    NONE    5
stop_cnt_hwpr    NONE    5
rel_move_hwpr    NONE    5
stat_control_hwpr    NONE    5
pot_targ_hwpr    NONE    5
mode_act    NONE    5
enc_targ_hwpr    NONE    5
enc_err_hwpr    NONE    5
dr_0_act    NONE    5
dr_1_act    NONE    5
dr_2_act    NONE    5
tol_act    NONE    5
status_actbus    NONE    5
used_actbus    NONE    5
pot_err_hwpr    NONE    5
blob_idx_sbsc    NONE    5
el_raw_enc    NONE    100
_TLM_CHECKSUM_
el_enc    NONE    100
_TLM_CHECKSUM_
sigma_enc    NONE    100
_TLM_CHECKSUM_
el_motor_enc    NONE    100
_TLM_CHECKSUM_
sigma_motor_enc    NONE    100
_TLM_CHECKSUM_
chatter    NONE    100
_TLM_CHECKSUM_
focpos_sbsc    NONE    5
delay_sbsc    NONE    5
daz_p    NONE    5
steps_shutter    NONE    5
steps_slow_shutter    NONE    5
pos_shutter    NONE    5
ra_sbsc    NONE    5
dec_sbsc    NONE    5
i_tot    NONE    5
t_set_sbsc    NONE    5
pot_hwpr    NONE    5
t_cpu0_flc_s    NONE    1
t_cpu0_flc_n    NONE    1
t_cpu1_flc_s    NONE    1
t_cpu1_flc_n    NONE    1
v_12v_flc_s    NONE    1
v_12v_flc_n    NONE    1
v_5v_flc_s    NONE    1
v_5v_flc_n    NONE    1
v_batt_flc_s    NONE    1
v_batt_flc_n    NONE    1
i_flc_s    NONE    1
i_flc_n    NONE    1
last_cmd_s    NONE    5
last_cmd_n    NONE    5
count_cmd_s    NONE    5
count_cmd_n    NONE    5
df_flc_s    NONE    5
df_flc_n    NONE    5
time_flc_s    NONE    100
_TLM_CHECKSUM_
time_flc_n    NONE    100
_TLM_CHECKSUM_
timeout_s    NONE    5
timeout_n    NONE    5
t_start_cycle    NONE    5
t_pot_max_cycle    NONE    5
t_char_max_cycle    NONE    5
t_char_set_cycle    NONE    5
time_char_cycle    NONE    5
time_set_cycle    NONE    5
thresh_atrim    NONE    5
time_atrim    NONE    5
rate_atrim    NONE    5
v_batt_cc2    NONE    1
v_arr_cc2    NONE    1
i_batt_cc2    NONE    1
i_arr_cc2    NONE    1
t_hs_cc2    NONE    1
fault_cc2    NONE    1
alarm_cc2    NONE    1
v_targ_cc2    NONE    1
state_cc2    NONE    1
led_cc2    NONE    1
latch0    NONE    5
latch1    NONE    5
switch_gy    NONE    5
switch_misc    NONE    5
bus_reset_act    NONE    5
v_pump_bal    NONE    5
dac2_ampl    NONE    5
_TLM_CHECKSUM_
mask_gy    NONE    5
bits_vtx    NONE    5
bits_bal    NONE    5
pch_pyr_clin    NONE    5
roll_pyr_clin    NONE    5
xel_if_clin    NONE    5
el_raw_if_clin    NONE    5
x_stage    NONE    5
y_stage    NONE    5
ifpm_hall    NONE    5
lvdt_65_act    NONE    5
lvdt_63_act    NONE    5
lvdt_64_act    NONE    5
ifyaw_1_gy    NONE    200
_TLM_CHECKSUM_
ifroll_1_gy    NONE    200
_TLM_CHECKSUM_
ifyaw_2_gy    NONE    200
_TLM_CHECKSUM_
ifel_1_gy    NONE    200
_TLM_CHECKSUM_
ifel_2_gy    NONE    200
_TLM_CHECKSUM_
ifroll_2_gy    NONE    200
_TLM_CHECKSUM_
good_pktcnt_yaw_1_gy    NONE    200
_TLM_CHECKSUM_
good_pktcnt_roll_1_gy    NONE    200
_TLM_CHECKSUM_
good_pktcnt_el_1_gy    NONE    200
_TLM_CHECKSUM_
good_pktcnt_yaw_2_gy    NONE    200
_TLM_CHECKSUM_
good_pktcnt_roll_2_gy    NONE    200
_TLM_CHECKSUM_
good_pktcnt_el_2_gy    NONE    200
_TLM_CHECKSUM_
az    NONE    200
_TLM_CHECKSUM_
el    NONE    200
_TLM_CHECKSUM_
ifel_gy    NONE    100
_TLM_CHECKSUM_
ifroll_gy    NONE    100
_TLM_CHECKSUM_
ifyaw_gy    NONE    100
_TLM_CHECKSUM_
vel_req_el    NONE    200
_TLM_CHECKSUM_
vel_req_az    NONE    200
_TLM_CHECKSUM_
trigger_xsc    NONE    100
dig43_das    NONE    100
_TLM_CHECKSUM_
chopper    NONE    100
_TLM_CHECKSUM_
x_mag1_n    NONE    100
_TLM_CHECKSUM_
y_mag1_n    NONE    100
_TLM_CHECKSUM_
z_mag1_n    NONE    100
_TLM_CHECKSUM_
x_mag2_s    NONE    100
_TLM_CHECKSUM_
y_mag2_s    NONE    100
_TLM_CHECKSUM_
z_mag2_s    NONE    100
_TLM_CHECKSUM_
lat_dgps    NONE    1
lon_dgps    NONE    1
alt_dgps    NONE    1
num_sat_dgps    NONE    1
quality_dgps    NONE    1
az_raw_dgps    NONE    5
az_dgps    NONE    5
sigma_dgps    NONE    1
ifel_earth_gy    NONE    5
ifroll_earth_gy    NONE    5
ifyaw_earth_gy    NONE    5
az_mag1    NONE    5
az_raw_mag1    NONE    5
pitch_mag1    NONE    5
sigma_mag1    NONE    5
declination_mag1    NONE    5
dip_mag1    NONE    5
cal_xmax_mag1    NONE    1
cal_xmin_mag1    NONE    1
cal_ymax_mag1    NONE    1
cal_ymin_mag1    NONE    1
cal_align_mag1    NONE    1
az_mag2    NONE    5
az_raw_mag2    NONE    5
pitch_mag2    NONE    5
sigma_mag2    NONE    5
declination_mag2    NONE    5
dip_mag2    NONE    5
cal_xmax_mag2    NONE    1
_TLM_CHECKSUM_
cal_xmin_mag2    NONE    1
cal_ymax_mag2    NONE    1
cal_ymin_mag2    NONE    1
cal_align_mag2    NONE    1
mc_rw_vel    NONE    100
_TLM_CHECKSUM_
mc_rw_pos    NONE    100
_TLM_CHECKSUM_
mc_el_vel    NONE    100
_TLM_CHECKSUM_
mc_el_pos    NONE    100
_TLM_CHECKSUM_
mc_el_motor_pos    NONE    100
_TLM_CHECKSUM_
mc_piv_vel    NONE    100
_TLM_CHECKSUM_
mc_piv_pos    NONE    100
_TLM_CHECKSUM_
control_word_read_el    NONE    5
control_word_read_rw    NONE    5
control_word_read_piv    NONE    5
latched_fault_el    NONE    5
latched_fault_rw    NONE    5
latched_fault_piv    NONE    5
network_status_el    NONE    5
network_status_rw    NONE    5
network_status_piv    NONE    5
network_problem_el    NONE    5
network_problem_rw    NONE    5
network_problem_piv    NONE    5
mc_cmd_status    NONE    5
mc_piv_i_cmd    NONE    200
_TLM_CHECKSUM_
mc_rw_i_cmd    NONE    200
_TLM_CHECKSUM_
mc_el_i_cmd    NONE    200
_TLM_CHECKSUM_
mc_piv_i_read    NONE    200
_TLM_CHECKSUM_
mc_rw_i_read    NONE    200
_TLM_CHECKSUM_
mc_el_i_read    NONE    200
_TLM_CHECKSUM_
g_p_el    NONE    5
g_i_el    NONE    5
g_d_el    NONE    5
g_db_el    NONE    5
g_p_az    NONE    5
g_i_az    NONE    5
g_d_az    NONE    5
g_pe_piv    NONE    5
g_pv_piv    NONE    5
g_iv_piv    NONE    5
_TLM_CHECKSUM_
set_rw    NONE    5
fault_gy    NONE    5
vel_el_p    NONE    200
_TLM_CHECKSUM_
frict_off_piv    NONE    200
_TLM_CHECKSUM_
frict_term_piv    NONE    200
_TLM_CHECKSUM_
frict_term_uf_piv    NONE    200
_TLM_CHECKSUM_
frict_off_el    NONE    200
_TLM_CHECKSUM_
frict_term_el    NONE    200
_TLM_CHECKSUM_
frict_term_uf_el    NONE    200
_TLM_CHECKSUM_
status_rw    NONE    5
state_rw    NONE    5
status_el    NONE    5
state_el    NONE    5
status_piv    NONE    5
state_piv    NONE    5
t_mc_rw    NONE    5
t_mc_el    NONE    5
t_mc_piv    NONE    5
p_term_el    NONE    200
_TLM_CHECKSUM_
i_term_el    NONE    200
_TLM_CHECKSUM_
d_term_el    NONE    200
_TLM_CHECKSUM_
error_el    NONE    200
_TLM_CHECKSUM_
el_integral_step    NONE    200
_TLM_CHECKSUM_
p_term_az    NONE    200
_TLM_CHECKSUM_
i_term_az    NONE    200
_TLM_CHECKSUM_
d_term_az    NONE    200
_TLM_CHECKSUM_
error_az    NONE    200
_TLM_CHECKSUM_
az_integral_step    NONE    200
_TLM_CHECKSUM_
p_rw_term_piv    NONE    200
_TLM_CHECKSUM_
i_rw_term_piv    NONE    200
_TLM_CHECKSUM_
p_err_term_piv    NONE    200
_TLM_CHECKSUM_
dio_heaters    NONE    100
_TLM_CHECKSUM_
ain00_cryo_labjack    NONE    5
ain01_cryo_labjack    NONE    5
ain02_cryo_labjack    NONE    5
ain03_cryo_labjack    NONE    5
ain04_cryo_labjack    NONE    5
ain05_cryo_labjack    NONE    5
ain06_cryo_labjack    NONE    5
ain07_cryo_labjack    NONE    5
ain08_cryo_labjack    NONE    5
ain09_cryo_labjack    NONE    5
ain10_cryo_labjack    NONE    5
ain11_cryo_labjack    NONE    5
ain12_cryo_labjack    NONE    5
ain13_cryo_labjack    NONE    5
ain14_cryo_labjack    NONE    5
mcp_1hz_framecount    NONE    1
mcp_1hz_framecount_dl    NONE    1
mcp_5hz_framecount    NONE    5
mcp_100hz_framecount    NONE    100
_TLM_CHECKSUM_
mcp_200hz_framecount    NONE    200
_TLM_CHECKSUM_
mcp_244hz_framecount    NONE    244
_TLM_CHECKSUM_
mcp_488hz_framecount    NONE    488
_TLM_CHECKSUM_
ctime_packet_roach1    NONE    488
_TLM_CHECKSUM_
ctime_packet_roach2    NONE    488
_TLM_CHECKSUM_
ctime_packet_roach3    NONE    488
_TLM_CHECKSUM_
ctime_packet_roach4    NONE    488
_TLM_CHECKSUM_
ctime_packet_roach5    NONE    488
_TLM_CHECKSUM_
pps_count_roach1    NONE    488
_TLM_CHECKSUM_
pps_count_roach2    NONE    488
_TLM_CHECKSUM_
pps_count_roach3    NONE    488
_TLM_CHECKSUM_
pps_count_roach4    NONE    488
_TLM_CHECKSUM_
pps_count_roach5    NONE    488
_TLM_CHECKSUM_
clock_count_roach1    NONE    488
_TLM_CHECKSUM_
clock_count_roach2    NONE    488
_TLM_CHECKSUM_
clock_count_roach3    NONE    488
_TLM_CHECKSUM_
clock_count_roach4    NONE    488
_TLM_CHECKSUM_
clock_count_roach5    NONE    488
_TLM_CHECKSUM_
packet_count_roach1    NONE    488
_TLM_CHECKSUM_
packet_count_roach2    NONE    488
_TLM_CHECKSUM_
packet_count_roach3    NONE    488
_TLM_CHECKSUM_
packet_count_roach4    NONE    488
_TLM_CHECKSUM_
packet_count_roach5    NONE    488
_TLM_CHECKSUM_
packet_count_mcp_roach1    NONE    5
packet_count_mcp_roach2    NONE    5
packet_count_mcp_roach3    NONE    5
packet_count_mcp_roach4    NONE    5
packet_count_mcp_roach5    NONE    5
packet_count_valid_mcp_roach1    NONE    5
packet_count_valid_mcp_roach2    NONE    5
packet_count_valid_mcp_roach3    NONE    5
packet_count_valid_mcp_roach4    NONE    5
packet_count_valid_mcp_roach5    NONE    5
_TLM_CHECKSUM_
packet_count_invalid_mcp_roach1    NONE    5
packet_count_invalid_mcp_roach2    NONE    5
packet_count_invalid_mcp_roach3    NONE    5
packet_count_invalid_mcp_roach4    NONE    5
packet_count_invalid_mcp_roach5    NONE    5
state_pi_roach1    NONE    5
state_pi_roach2    NONE    5
state_pi_roach3    NONE    5
state_pi_roach4    NONE    5
state_pi_roach5    NONE    5
state_roach1    NONE    5
state_roach2    NONE    5
state_roach3    NONE    5
state_roach4    NONE    5
state_roach5    NONE    5
_TLM_CHECKSUM_
stream_state_roach1    NONE    5
stream_state_roach2    NONE    5
stream_state_roach3    NONE    5
stream_state_roach4    NONE    5
stream_state_roach5    NONE    5
is_averaging_roach1    NONE    5
is_averaging_roach2    NONE    5
is_averaging_roach3    NONE    5
is_averaging_roach4    NONE    5
is_averaging_roach5    NONE    5
fk_smooth_scale_roach1    NONE    5
fk_smooth_scale_roach2    NONE    5
fk_smooth_scale_roach3    NONE    5
fk_smooth_scale_roach4    NONE    5
fk_smooth_scale_roach5    NONE    5
fk_peak_thresh_roach1    NONE    5
fk_peak_thresh_roach2    NONE    5
fk_peak_thresh_roach3    NONE    5
_TLM_CHECKSUM_
fk_peak_thresh_roach4    NONE    5
fk_peak_thresh_roach5    NONE    5
fk_space_thresh_roach1    NONE    5
fk_space_thresh_roach2    NONE    5
fk_space_thresh_roach3    NONE    5
fk_space_thresh_roach4    NONE    5
fk_space_thresh_roach5    NONE    5
atten_in_roach1    NONE    5
atten_in_roach2    NONE    5
atten_in_roach3    NONE    5
atten_in_roach4    NONE    5
atten_in_roach5    NONE    5
atten_out_roach1    NONE    5
atten_out_roach2    NONE    5
atten_out_roach3    NONE    5
_TLM_CHECKSUM_
atten_out_roach4    NONE    5
atten_out_roach5    NONE    5
adcI_rms_roach1    NONE    5
adcI_rms_roach2    NONE    5
adcI_rms_roach3    NONE    5
adcI_rms_roach4    NONE    5
adcI_rms_roach5    NONE    5
adcQ_rms_roach1    NONE    5
adcQ_rms_roach2    NONE    5
adcQ_rms_roach3    NONE    5
adcQ_rms_roach4    NONE    5
_TLM_CHECKSUM_
adcQ_rms_roach5    NONE    5
nkids_found_roach1    NONE    1
nkids_found_roach2    NONE    1
nkids_found_roach3    NONE    1
nkids_found_roach4    NONE    1
nkids_found_roach5    NONE    1
nkids_good_roach1    NONE    1
nkids_good_roach2    NONE    1
nkids_good_roach3    NONE    1
nkids_good_roach4    NONE    1
nkids_good_roach5    NONE    1
nkids_bad_roach1    NONE    1
nkids_bad_roach2    NONE    1
nkids_bad_roach3    NONE    1
nkids_bad_roach4    NONE    1
nkids_bad_roach5    NONE    1
status_roach1    NONE    1
status_roach2    NONE    1
status_roach3    NONE    1
status_roach4    NONE    1
status_roach5    NONE    1
current_ntones_roach1    NONE    1
current_ntones_roach2    NONE    1
current_ntones_roach3    NONE    1
current_ntones_roach4    NONE    1
current_ntones_roach5    NONE    1
lo_freq_req_roach1    NONE    1
lo_freq_req_roach2    NONE    1
lo_freq_req_roach3    NONE    1
lo_freq_req_roach4    NONE    1
lo_freq_req_roach5    NONE    1
lo_center_freq_roach1    NONE    1
lo_center_freq_roach2    NONE    1
lo_center_freq_roach3    NONE    1
lo_center_freq_roach4    NONE    1
lo_center_freq_roach5    NONE    1
nflag_thresh_roach1    NONE    1
nflag_thresh_roach2    NONE    1
nflag_thresh_roach3    NONE    1
nflag_thresh_roach4    NONE    1
nflag_thresh_roach5    NONE    1
kidA_roachN    NONE    488
_TLM_CHECKSUM_
kidB_roachN    NONE    488
_TLM_CHECKSUM_
kidC_roachN    NONE    488
_TLM_CHECKSUM_
kidD_roachN    NONE    488
_TLM_CHECKSUM_
kidE_roachN    NONE    488
_TLM_CHECKSUM_
kidF_roachN    NONE    488
_TLM_CHECKSUM_
kidG_roachN    NONE    488
_TLM_CHECKSUM_
kidH_roachN    NONE    488
_TLM_CHECKSUM_
kidI_roachN    NONE    488
_TLM_CHECKSUM_
kidJ_roachN    NONE    488
_TLM_CHECKSUM_
kidK_roachN    NONE    488
_TLM_CHECKSUM_
kidL_roachN    NONE    488
_TLM_CHECKSUM_
kidM_roachN    NONE    488
_TLM_CHECKSUM_
kidN_roachN    NONE    488
_TLM_CHECKSUM_
kidO_roachN    NONE    488
_TLM_CHECKSUM_
kidA_roachN_index    NONE    488
_TLM_CHECKSUM_
kidB_roachN_index    NONE    488
_TLM_CHECKSUM_
kidC_roachN_index    NONE    488
_TLM_CHECKSUM_
kidD_roachN_index    NONE    488
_TLM_CHECKSUM_
kidE_roachN_index    NONE    488
_TLM_CHECKSUM_
kidF_roachN_index    NONE    488
_TLM_CHECKSUM_
kidG_roachN_index    NONE    488
_TLM_CHECKSUM_
kidH_roachN_index    NONE    488
_TLM_CHECKSUM_
kidI_roachN_index    NONE    488
_TLM_CHECKSUM_
kidJ_roachN_index    NONE    488
_TLM_CHECKSUM_
kidK_roachN_index    NONE    488
_TLM_CHECKSUM_
kidL_roachN_index    NONE    488
_TLM_CHECKSUM_
kidM_roachN_index    NONE    488
_TLM_CHECKSUM_
kidN_roachN_index    NONE    488
_TLM_CHECKSUM_
kidO_roachN_index    NONE    488
_TLM_CHECKSUM_
flags_kids0000_roach1    NONE    1
flags_kids0016_roach1    NONE    1
flags_kids0032_roach1    NONE    1
flags_kids0048_roach1    NONE    1
flags_kids0064_roach1    NONE    1
flags_kids0080_roach1    NONE    1
flags_kids0096_roach1    NONE    1
flags_kids0112_roach1    NONE    1
flags_kids0128_roach1    NONE    1
flags_kids0144_roach1    NONE    1
flags_kids0160_roach1    NONE    1
flags_kids0176_roach1    NONE    1
flags_kids0192_roach1    NONE    1
flags_kids0208_roach1    NONE    1
flags_kids0224_roach1    NONE    1
flags_kids0240_roach1    NONE    1
flags_kids0256_roach1    NONE    1
flags_kids0272_roach1    NONE    1
flags_kids0288_roach1    NONE    1
flags_kids0304_roach1    NONE    1
flags_kids0320_roach1    NONE    1
flags_kids0336_roach1    NONE    1
flags_kids0352_roach1    NONE    1
flags_kids0368_roach1    NONE    1
flags_kids0384_roach1    NONE    1
flags_kids0400_roach1    NONE    1
flags_kids0416_roach1    NONE    1
flags_kids0432_roach1    NONE    1
flags_kids0448_roach1    NONE    1
flags_kids0464_roach1    NONE    1
flags_kids0480_roach1    NONE    1
flags_kids0496_roach1    NONE    1
flags_kids0512_roach1    NONE    1
flags_kids0528_roach1    NONE    1
flags_kids0544_roach1    NONE    1
flags_kids0560_roach1    NONE    1
flags_kids0576_roach1    NONE    1
flags_kids0592_roach1    NONE    1
flags_kids0608_roach1    NONE    1
flags_kids0624_roach1    NONE    1
flags_kids0640_roach1    NONE    1
flags_kids0656_roach1    NONE    1
flags_kids0672_roach1    NONE    1
flags_kids0688_roach1    NONE    1
flags_kids0704_roach1    NONE    1
flags_kids0720_roach1    NONE    1
flags_kids0736_roach1    NONE    1
flags_kids0752_roach1    NONE    1
flags_kids0768_roach1    NONE    1
flags_kids0784_roach1    NONE    1
flags_kids0800_roach1    NONE    1
flags_kids0816_roach1    NONE    1
flags_kids0832_roach1    NONE    1
flags_kids0848_roach1    NONE    1
flags_kids0864_roach1    NONE    1
flags_kids0880_roach1    NONE    1
flags_kids0896_roach1    NONE    1
flags_kids0912_roach1    NONE    1
flags_kids0928_roach1    NONE    1
flags_kids0944_roach1    NONE    1
flags_kids0960_roach1    NONE    1
flags_kids0976_roach1    NONE    1
flags_kids0992_roach1    NONE    1
flags_kids1008_roach1    NONE    1
flags_kids0000_roach2    NONE    1
flags_kids0016_roach2    NONE    1
flags_kids0032_roach2    NONE    1
flags_kids0048_roach2    NONE    1
flags_kids0064_roach2    NONE    1
flags_kids0080_roach2    NONE    1
flags_kids0096_roach2    NONE    1
flags_kids0112_roach2    NONE    1
flags_kids0128_roach2    NONE    1
flags_kids0144_roach2    NONE    1
flags_kids0160_roach2    NONE    1
flags_kids0176_roach2    NONE    1
flags_kids0192_roach2    NONE    1
flags_kids0208_roach2    NONE    1
flags_kids0224_roach2    NONE    1
flags_kids0240_roach2    NONE    1
flags_kids0256_roach2    NONE    1
flags_kids0272_roach2    NONE    1
flags_kids0288_roach2    NONE    1
flags_kids0304_roach2    NONE    1
flags_kids0320_roach2    NONE    1
flags_kids0336_roach2    NONE    1
flags_kids0352_roach2    NONE    1
flags_kids0368_roach2    NONE    1
flags_kids0384_roach2    NONE    1
flags_kids0400_roach2    NONE    1
flags_kids0416_roach2    NONE    1
flags_kids0432_roach2    NONE    1
flags_kids0448_roach2    NONE    1
flags_kids0464_roach2    NONE    1
flags_kids0480_roach2    NONE    1
flags_kids0496_roach2    NONE    1
flags_kids0512_roach2    NONE    1
flags_kids0528_roach2    NONE    1
flags_kids0544_roach2    NONE    1
flags_kids0560_roach2    NONE    1
_TLM_CHECKSUM_
flags_kids0576_roach2    NONE    1
flags_kids0592_roach2    NONE    1
flags_kids0608_roach2    NONE    1
flags_kids0624_roach2    NONE    1
flags_kids0640_roach2    NONE    1
flags_kids0656_roach2    NONE    1
flags_kids0672_roach2    NONE    1
flags_kids0688_roach2    NONE    1
flags_kids0704_roach2    NONE    1
flags_kids0720_roach2    NONE    1
flags_kids0736_roach2    NONE    1
flags_kids0752_roach2    NONE    1
flags_kids0768_roach2    NONE    1
flags_kids0784_roach2    NONE    1
flags_kids0800_roach2    NONE    1
flags_kids0816_roach2    NONE    1
flags_kids0832_roach2    NONE    1
flags_kids0848_roach2    NONE    1
flags_kids0864_roach2    NONE    1
flags_kids0880_roach2    NONE    1
flags_kids0896_roach2    NONE    1
flags_kids0912_roach2    NONE    1
flags_kids0928_roach2    NONE    1
flags_kids0944_roach2    NONE    1
flags_kids0960_roach2    NONE    1
flags_kids0976_roach2    NONE    1
flags_kids0992_roach2    NONE    1
flags_kids1008_roach2    NONE    1
flags_kids0000_roach3    NONE    1
flags_kids0016_roach3    NONE    1
flags_kids0032_roach3    NONE    1
flags_kids0048_roach3    NONE    1
flags_kids0064_roach3    NONE    1
flags_kids0080_roach3    NONE    1
flags_kids0096_roach3    NONE    1
flags_kids0112_roach3    NONE    1
flags_kids0128_roach3    NONE    1
flags_kids0144_roach3    NONE    1
flags_kids0160_roach3    NONE    1
flags_kids0176_roach3    NONE    1
flags_kids0192_roach3    NONE    1
flags_kids0208_roach3    NONE    1
flags_kids0224_roach3    NONE    1
flags_kids0240_roach3    NONE    1
flags_kids0256_roach3    NONE    1
flags_kids0272_roach3    NONE    1
flags_kids0288_roach3    NONE    1
flags_kids0304_roach3    NONE    1
flags_kids0320_roach3    NONE    1
flags_kids0336_roach3    NONE    1
flags_kids0352_roach3    NONE    1
flags_kids0368_roach3    NONE    1
flags_kids0384_roach3    NONE    1
flags_kids0400_roach3    NONE    1
flags_kids0416_roach3    NONE    1
flags_kids0432_roach3    NONE    1
flags_kids0448_roach3    NONE    1
flags_kids0464_roach3    NONE    1
flags_kids0480_roach3    NONE    1
flags_kids0496_roach3    NONE    1
flags_kids0512_roach3    NONE    1
flags_kids0528_roach3    NONE    1
flags_kids0544_roach3    NONE    1
flags_kids0560_roach3    NONE    1
flags_kids0576_roach3    NONE    1
flags_kids0592_roach3    NONE    1
flags_kids0608_roach3    NONE    1
flags_kids0624_roach3    NONE    1
flags_kids0640_roach3    NONE    1
flags_kids0656_roach3    NONE    1
flags_kids0672_roach3    NONE    1
flags_kids0688_roach3    NONE    1
flags_kids0704_roach3    NONE    1
flags_kids0720_roach3    NONE    1
flags_kids0736_roach3    NONE    1
flags_kids0752_roach3    NONE    1
flags_kids0768_roach3    NONE    1
flags_kids0784_roach3    NONE    1
flags_kids0800_roach3    NONE    1
flags_kids0816_roach3    NONE    1
flags_kids0832_roach3    NONE    1
flags_kids0848_roach3    NONE    1
flags_kids0864_roach3    NONE    1
flags_kids0880_roach3    NONE    1
flags_kids0896_roach3    NONE    1
flags_kids0912_roach3    NONE    1
flags_kids0928_roach3    NONE    1
flags_kids0944_roach3    NONE    1
flags_kids0960_roach3    NONE    1
flags_kids0976_roach3    NONE    1
flags_kids0992_roach3    NONE    1
flags_kids1008_roach3    NONE    1
flags_kids0000_roach4    NONE    1
flags_kids0016_roach4    NONE    1
flags_kids0032_roach4    NONE    1
flags_kids0048_roach4    NONE    1
flags_kids0064_roach4    NONE    1
flags_kids0080_roach4    NONE    1
flags_kids0096_roach4    NONE    1
flags_kids0112_roach4    NONE    1
_TLM_CHECKSUM_
flags_kids0128_roach4    NONE    1
flags_kids0144_roach4    NONE    1
flags_kids0160_roach4    NONE    1
flags_kids0176_roach4    NONE    1
flags_kids0192_roach4    NONE    1
flags_kids0208_roach4    NONE    1
flags_kids0224_roach4    NONE    1
flags_kids0240_roach4    NONE    1
flags_kids0256_roach4    NONE    1
flags_kids0272_roach4    NONE    1
flags_kids0288_roach4    NONE    1
flags_kids0304_roach4    NONE    1
flags_kids0320_roach4    NONE    1
flags_kids0336_roach4    NONE    1
flags_kids0352_roach4    NONE    1
flags_kids0368_roach4    NONE    1
flags_kids0384_roach4    NONE    1
flags_kids0400_roach4    NONE    1
flags_kids0416_roach4    NONE    1
flags_kids0432_roach4    NONE    1
flags_kids0448_roach4    NONE    1
flags_kids0464_roach4    NONE    1
flags_kids0480_roach4    NONE    1
flags_kids0496_roach4    NONE    1
flags_kids0512_roach4    NONE    1
flags_kids0528_roach4    NONE    1
flags_kids0544_roach4    NONE    1
flags_kids0560_roach4    NONE    1
flags_kids0576_roach4    NONE    1
flags_kids0592_roach4    NONE    1
flags_kids0608_roach4    NONE    1
flags_kids0624_roach4    NONE    1
flags_kids0640_roach4    NONE    1
flags_kids0656_roach4    NONE    1
flags_kids0672_roach4    NONE    1
flags_kids0688_roach4    NONE    1
flags_kids0704_roach4    NONE    1
flags_kids0720_roach4    NONE    1
flags_kids0736_roach4    NONE    1
flags_kids0752_roach4    NONE    1
flags_kids0768_roach4    NONE    1
flags_kids0784_roach4    NONE    1
flags_kids0800_roach4    NONE    1
flags_kids0816_roach4    NONE    1
flags_kids0832_roach4    NONE    1
flags_kids0848_roach4    NONE    1
flags_kids0864_roach4    NONE    1
flags_kids0880_roach4    NONE    1
flags_kids0896_roach4    NONE    1
flags_kids0912_roach4    NONE    1
flags_kids0928_roach4    NONE    1
flags_kids0944_roach4    NONE    1
flags_kids0960_roach4    NONE    1
flags_kids0976_roach4    NONE    1
flags_kids0992_roach4    NONE    1
flags_kids1008_roach4    NONE    1
flags_kids0000_roach5    NONE    1
flags_kids0016_roach5    NONE    1
flags_kids0032_roach5    NONE    1
flags_kids0048_roach5    NONE    1
flags_kids0064_roach5    NONE    1
flags_kids0080_roach5    NONE    1
flags_kids0096_roach5    NONE    1
flags_kids0112_roach5    NONE    1
flags_kids0128_roach5    NONE    1
flags_kids0144_roach5    NONE    1
flags_kids0160_roach5    NONE    1
flags_kids0176_roach5    NONE    1
flags_kids0192_roach5    NONE    1
flags_kids0208_roach5    NONE    1
flags_kids0224_roach5    NONE    1
flags_kids0240_roach5    NONE    1
flags_kids0256_roach5    NONE    1
flags_kids0272_roach5    NONE    1
flags_kids0288_roach5    NONE    1
flags_kids0304_roach5    NONE    1
flags_kids0320_roach5    NONE    1
flags_kids0336_roach5    NONE    1
flags_kids0352_roach5    NONE    1
flags_kids0368_roach5    NONE    1
flags_kids0384_roach5    NONE    1
flags_kids0400_roach5    NONE    1
flags_kids0416_roach5    NONE    1
flags_kids0432_roach5    NONE    1
flags_kids0448_roach5    NONE    1
flags_kids0464_roach5    NONE    1
flags_kids0480_roach5    NONE    1
flags_kids0496_roach5    NONE    1
flags_kids0512_roach5    NONE    1
flags_kids0528_roach5    NONE    1
flags_kids0544_roach5    NONE    1
flags_kids0560_roach5    NONE    1
flags_kids0576_roach5    NONE    1
flags_kids0592_roach5    NONE    1
flags_kids0608_roach5    NONE    1
flags_kids0624_roach5    NONE    1
flags_kids0640_roach5    NONE    1
flags_kids0656_roach5    NONE    1
flags_kids0672_roach5    NONE    1
flags_kids0688_roach5    NONE    1
_TLM_CHECKSUM_
flags_kids0704_roach5    NONE    1
flags_kids0720_roach5    NONE    1
flags_kids0736_roach5    NONE    1
flags_kids0752_roach5    NONE    1
flags_kids0768_roach5    NONE    1
flags_kids0784_roach5    NONE    1
flags_kids0800_roach5    NONE    1
flags_kids0816_roach5    NONE    1
flags_kids0832_roach5    NONE    1
flags_kids0848_roach5    NONE    1
flags_kids0864_roach5    NONE    1
flags_kids0880_roach5    NONE    1
flags_kids0896_roach5    NONE    1
flags_kids0912_roach5    NONE    1
flags_kids0928_roach5    NONE    1
flags_kids0944_roach5    NONE    1
flags_kids0960_roach5    NONE    1
flags_kids0976_roach5    NONE    1
flags_kids0992_roach5    NONE    1
flags_kids1008_roach5    NONE    1
