#
# Linklist "balance_system.ll" Format File
# Auto-generated by linklist
#
# Serial=956d2db7
# Blk Size=26
# Frames per file=900
#
LL_NO_AUTO_CHECKSUM

vel_bal    NONE    1
acc_bal    NONE    1
i_move_bal    NONE    1
i_hold_bal    NONE    1
pos_bal    NONE    1
lim_bal    NONE    1
i_level_on_bal    NONE    1
i_level_off_bal    NONE    1
i_el_req_avg_bal    NONE    1
status_bal    NONE    1
