#
# Linklist "cryovalves.ll" Format File
# Auto-generated by linklist
#
# Serial=3cb65ed9
# Blk Size=33
# Frames per file=900
#
LL_NO_AUTO_CHECKSUM

lims_pumpvalve    NONE    1
lims_fillvalve    NONE    1
pos_pumpvalve    NONE    1
pos_fillvalve    NONE    1
enc_potvalve    NONE    1
pos_potvalve    NONE    1
state_potvalve    NONE    1
vel_potvalve    NONE    1
thresh_open_potvalve    NONE    1
vel_valves    NONE    1
acc_valves    NONE    1
i_open_potvalve    NONE    1
i_close_potvalve    NONE    1
