#
# Linklist "cryo_important.ll" Format File
# Auto-generated by linklist
#
# Serial=7a3f3840
# Blk Size=8609
# Frames per file=900
#
LL_NO_AUTO_CHECKSUM

status_500_LNA    NONE    1
cal_lamp_read    NONE    200
_TLM_CHECKSUM_
status_charcoal_hs    NONE    1
status_charcoal_heater    NONE    1
status_250_LNA    NONE    1
status_350_LNA    NONE    1
rox_bias    NONE    1
tr_he3_fridge    NONE    200
_TLM_CHECKSUM_
tr_he4_pot    NONE    200
_TLM_CHECKSUM_
tr_250_fpa    NONE    200
_TLM_CHECKSUM_
labjack_conn_status    NONE    1
td_charcoal_hs    NONE    200
_TLM_CHECKSUM_
td_charcoal    NONE    200
_TLM_CHECKSUM_
td_1k_fridge    NONE    200
_TLM_CHECKSUM_
level_sensor_read    NONE    1
td_4k_plate    NONE    200
_TLM_CHECKSUM_
td_vcs1_filt    NONE    200
_TLM_CHECKSUM_
td_m3    NONE    200
_TLM_CHECKSUM_
td_ob_filter    NONE    200
_TLM_CHECKSUM_
td_vcs2_plate    NONE    200
_TLM_CHECKSUM_
td_m4    NONE    200
_TLM_CHECKSUM_
td_4k_filt    NONE    200
_TLM_CHECKSUM_
td_vcs2_hx    NONE    200
_TLM_CHECKSUM_
td_vcs1_plate    NONE    200
_TLM_CHECKSUM_
td_vcs2_filt    NONE    200
_TLM_CHECKSUM_
td_hwp    NONE    200
_TLM_CHECKSUM_
td_vcs1_hx    NONE    200
_TLM_CHECKSUM_
tr_350_fpa    NONE    200
_TLM_CHECKSUM_
tr_500_fpa    NONE    200
_TLM_CHECKSUM_
of_status    NONE    1
if_status    NONE    1
thermistor_1    NONE    1
thermistor_2    NONE    1
thermistor_3    NONE    1
thermistor_4    NONE    1
thermistor_5    NONE    1
thermistor_6    NONE    1
thermistor_7    NONE    1
thermistor_8    NONE    1
thermistor_9    NONE    1
thermistor_10    NONE    1
thermistor_11    NONE    1
thermistor_12    NONE    1
thermistor_13    NONE    1
thermistor_14    NONE    1
thermistor_15    NONE    1
thermistor_16    NONE    1
thermistor_17    NONE    1
thermistor_18    NONE    1
thermistor_19    NONE    1
thermistor_20    NONE    1
thermistor_21    NONE    1
thermistor_22    NONE    1
thermistor_23    NONE    1
thermistor_24    NONE    1
thermistor_25    NONE    1
thermistor_26    NONE    1
thermistor_27    NONE    1
thermistor_28    NONE    1
thermistor_29    NONE    1
thermistor_30    NONE    1
thermistor_31    NONE    1
thermistor_32    NONE    1
thermistor_33    NONE    1
thermistor_34    NONE    1
thermistor_35    NONE    1
thermistor_36    NONE    1
thermistor_37    NONE    1
thermistor_38    NONE    1
thermistor_39    NONE    1
thermistor_40    NONE    1
thermistor_41    NONE    1
thermistor_42    NONE    1
thermistor_43    NONE    1
thermistor_44    NONE    1
thermistor_45    NONE    1
thermistor_46    NONE    1
thermistor_47    NONE    1
thermistor_48    NONE    1
thermistor_49    NONE    1
thermistor_50    NONE    1
thermistor_51    NONE    1
thermistor_52    NONE    1
thermistor_53    NONE    1
thermistor_54    NONE    1
thermistor_55    NONE    1
thermistor_56    NONE    1
thermistor_57    NONE    1
thermistor_58    NONE    1
thermistor_59    NONE    1
thermistor_60    NONE    1
thermistor_61    NONE    1
thermistor_62    NONE    1
thermistor_63    NONE    1
thermistor_64    NONE    1
thermistor_65    NONE    1
thermistor_66    NONE    1
thermistor_67    NONE    1
thermistor_68    NONE    1
thermistor_69    NONE    1
thermistor_70    NONE    1
thermistor_71    NONE    1
thermistor_72    NONE    1
thermistor_73    NONE    1
thermistor_74    NONE    1
