#
# Linklist "gps_status.ll" Format File
# Auto-generated by linklist
#
# Serial=42c3ee82
# Blk Size=38
# Frames per file=900
#
LL_NO_AUTO_CHECKSUM

lat    NONE    1
lon    NONE    1
alt    NONE    1
alt_sip    NONE    1
lat_sip    NONE    1
lon_sip    NONE    1
lat_dgps    NONE    1
lat_dgps    NONE    1
lat_dgps    NONE    1
lon_dgps    NONE    1
alt_dgps    NONE    1
num_sat_dgps    NONE    1
quality_dgps    NONE    1
az_raw_dgps    NONE    1
az_dgps    NONE    1
sigma_dgps    NONE    1
