#
# Linklist "hwpr.ll" Format File
# Auto-generated by linklist
#
# Serial=01ac7e45
# Blk Size=64
# Frames per file=900
#
LL_NO_AUTO_CHECKSUM

enc_hwpr    NONE    5
pos_hwpr    NONE    5
vel_hwpr    NONE    5
acc_hwpr    NONE    5
