#
# Linklist "lock.ll" Format File
# Auto-generated by linklist
#
# Serial=30b527ac
# Blk Size=94
# Frames per file=900
#
LL_NO_AUTO_CHECKSUM

state_lock    NONE    5
pin_in_lock    NONE    5
goal_lock    NONE    5
pot_lock    NONE    5
pos_lock    NONE    5
vel_lock    NONE    5
acc_lock    NONE    5
i_move_lock    NONE    5
i_hold_lock    NONE    5
