#
# Linklist "M2Actuators.ll" Format File
# Auto-generated by linklist
#
# Serial=29431c84
# Blk Size=144
# Frames per file=900
#
LL_NO_AUTO_CHECKSUM

status_actbus    NONE    5
pos_0_act    NONE    5
pos_1_act    NONE    5
pos_2_act    NONE    5
enc_0_act    NONE    5
enc_1_act    NONE    5
enc_2_act    NONE    5
vel_act    NONE    5
mode_act    NONE    5
tol_act    NONE    5
acc_act    NONE    5
i_hold_act    NONE    5
i_move_act    NONE    5
seized_act    NONE    5
