#
# Linklist "magnetometer.ll" Format File
# Auto-generated by linklist
#
# Serial=ebb622a4
# Blk Size=1370
# Frames per file=900
#
LL_NO_AUTO_CHECKSUM

x_mag1_n    NONE    100
_TLM_CHECKSUM_
y_mag1_n    NONE    100
_TLM_CHECKSUM_
z_mag1_n    NONE    100
_TLM_CHECKSUM_
x_mag2_s    NONE    100
_TLM_CHECKSUM_
y_mag2_s    NONE    100
_TLM_CHECKSUM_
z_mag2_s    NONE    100
_TLM_CHECKSUM_
az_mag1    NONE    5
az_raw_mag1    NONE    5
pitch_mag1    NONE    5
sigma_mag1    NONE    5
declination_mag1    NONE    5
dip_mag1    NONE    5
cal_xmax_mag1    NONE    1
cal_xmin_mag1    NONE    1
cal_ymax_mag1    NONE    1
cal_ymin_mag1    NONE    1
cal_align_mag1    NONE    1
az_mag2    NONE    5
az_raw_mag2    NONE    5
pitch_mag2    NONE    5
sigma_mag2    NONE    5
declination_mag2    NONE    5
dip_mag2    NONE    5
cal_xmax_mag2    NONE    1
cal_xmin_mag2    NONE    1
cal_ymax_mag2    NONE    1
cal_ymin_mag2    NONE    1
