#
# Linklist "motor_tests_small.ll" Format File
# Auto-generated by linklist
#
# Serial=67f3192d
# Blk Size=2018
# Frames per file=900
#
LL_NO_AUTO_CHECKSUM

el    NONE    100
_TLM_CHECKSUM_
az    NONE    100
_TLM_CHECKSUM_
mc_piv_i_cmd    NONE    10
mc_rw_i_cmd    NONE    10
mc_el_i_cmd    NONE    10
mc_piv_i_read    NONE    100
_TLM_CHECKSUM_
mc_rw_i_read    NONE    100
_TLM_CHECKSUM_
mc_el_i_read    NONE    100
_TLM_CHECKSUM_
mc_rw_vel    NONE    10
mc_el_motor_pos    NONE    100
_TLM_CHECKSUM_
mc_piv_vel    NONE    10
mc_piv_pos    NONE    10
network_status_el    NONE    1
network_status_rw    NONE    1
network_status_piv    NONE    1
network_problem_el    NONE    1
network_problem_rw    NONE    1
network_problem_piv    NONE    1
veto_sensor    NONE    5
