#
# Linklist "power_system.ll" Format File
# Auto-generated by linklist
#
# Serial=52da7f95
# Blk Size=62
# Frames per file=900
#
LL_NO_AUTO_CHECKSUM

v_batt_cc1    NONE    1
v_batt_cc2    NONE    1
i_batt_cc1    NONE    1
i_batt_cc2    NONE    1
v_arr_cc1    NONE    1
v_arr_cc2    NONE    1
i_arr_cc1    NONE    1
i_arr_cc2    NONE    1
state_cc1    NONE    1
state_cc2    NONE    1
t_hs_cc1    NONE    1
t_hs_cc2    NONE    1
current_eth_switch    NONE    1
current_fc1    NONE    1
current_xsc0    NONE    1
current_fc2    NONE    1
current_xsc1    NONE    1
current_ele_mot    NONE    1
current_pivot    NONE    1
current_rw_mot    NONE    1
current_hd_pv    NONE    1
current_gyros    NONE    1
current_data_transmit    NONE    1
fault_cc1    NONE    1
fault_cc2    NONE    1
alarm_cc1    NONE    1
alarm_cc2    NONE    1
v_targ_cc1    NONE    1
v_targ_cc2    NONE    1
