#
# Linklist "roach_status.ll" Format File
# Auto-generated by linklist
#
# Serial=2d511221
# Blk Size=10076
# Frames per file=900
#
LL_NO_AUTO_CHECKSUM

packet_count_roach1    NONE    488
_TLM_CHECKSUM_
packet_count_roach2    NONE    488
_TLM_CHECKSUM_
packet_count_roach3    NONE    488
_TLM_CHECKSUM_
packet_count_roach4    NONE    488
_TLM_CHECKSUM_
packet_count_roach5    NONE    488
_TLM_CHECKSUM_
packet_count_mcp_roach1    NONE    5
packet_count_mcp_roach2    NONE    5
packet_count_mcp_roach3    NONE    5
packet_count_mcp_roach4    NONE    5
packet_count_mcp_roach5    NONE    5
packet_count_valid_mcp_roach1    NONE    5
packet_count_valid_mcp_roach2    NONE    5
packet_count_valid_mcp_roach3    NONE    5
packet_count_valid_mcp_roach4    NONE    5
packet_count_valid_mcp_roach5    NONE    5
_TLM_CHECKSUM_
packet_count_invalid_mcp_roach1    NONE    5
packet_count_invalid_mcp_roach2    NONE    5
packet_count_invalid_mcp_roach3    NONE    5
packet_count_invalid_mcp_roach4    NONE    5
packet_count_invalid_mcp_roach5    NONE    5
