#
# Linklist "shared.ll" Format File
# Auto-generated by linklist
#
# Serial=2f2be549
# Blk Size=15715
# Frames per file=900
#
LL_NO_AUTO_CHECKSUM

status_mcc    NONE    5
he4_lev_old    NONE    5
he4_lev    NONE    5
time    NONE    100
_TLM_CHECKSUM_
time_usec    NONE    100
_TLM_CHECKSUM_
rate_highrate    NONE    1
rate_biphase    NONE    1
rate_pilot    NONE    1
mpsse_clock_speed    NONE    1
plover    NONE    5
status_eth    NONE    5
parts_sched    NONE    100
_TLM_CHECKSUM_
upslot_sched    NONE    5
t_cpu0_flc_n    NONE    1
t_cpu0_flc_s    NONE    1
t_cpu1_flc_n    NONE    1
t_cpu1_flc_s    NONE    1
v_12v_flc_n    NONE    1
v_12v_flc_s    NONE    1
v_5v_flc_n    NONE    1
v_5v_flc_s    NONE    1
v_batt_flc_n    NONE    1
v_batt_flc_s    NONE    1
i_flc_n    NONE    1
i_flc_s    NONE    1
last_cmd_n    NONE    5
last_cmd_s    NONE    5
count_cmd_n    NONE    5
count_cmd_s    NONE    5
df_flc_n    NONE    5
df_flc_s    NONE    5
time_flc_n    NONE    100
_TLM_CHECKSUM_
time_flc_s    NONE    100
_TLM_CHECKSUM_
timeout_n    NONE    5
timeout_s    NONE    5
test_values    NONE    200
_TLM_CHECKSUM_
heater_status_write    NONE    1
heater_status_read    NONE    1
cycle_state    NONE    1
stage_chopper    NONE    200
_TLM_CHECKSUM_
read_dio    NONE    1
tr_fpa_1k    NONE    200
_TLM_CHECKSUM_
tr_250_fpa    NONE    200
_TLM_CHECKSUM_
tr_1k_plate    NONE    200
_TLM_CHECKSUM_
tr_300mk_strap    NONE    200
_TLM_CHECKSUM_
tr_350_fpa    NONE    200
_TLM_CHECKSUM_
tr_he4_pot    NONE    200
_TLM_CHECKSUM_
tr_he3_fridge    NONE    200
_TLM_CHECKSUM_
tr_500_fpa    NONE    200
_TLM_CHECKSUM_
rox_bias    NONE    1
bias_alsa_state_rox    NONE    1
n2_flow_v    NONE    1
he_blow_v    NONE    1
he_pot_hi_flow_v    NONE    1
he_pot_lo_flow_v    NONE    1
he_purge_flow_v    NONE    1
alarm_gauge    NONE    1
td_charcoal_hs    NONE    200
_TLM_CHECKSUM_
td_vcs2_filt    NONE    200
_TLM_CHECKSUM_
td_250fpa    NONE    200
_TLM_CHECKSUM_
td_hwp    NONE    200
_TLM_CHECKSUM_
td_vcs1_hx    NONE    200
_TLM_CHECKSUM_
td_1k_fridge    NONE    200
_TLM_CHECKSUM_
td_4k_plate    NONE    200
_TLM_CHECKSUM_
td_vcs1_filt    NONE    200
_TLM_CHECKSUM_
td_m3    NONE    200
_TLM_CHECKSUM_
td_charcoal    NONE    200
_TLM_CHECKSUM_
td_ob_filter    NONE    200
_TLM_CHECKSUM_
td_vcs2_plate    NONE    200
_TLM_CHECKSUM_
td_m4    NONE    200
_TLM_CHECKSUM_
td_4k_filt    NONE    200
_TLM_CHECKSUM_
td_vcs2_hx    NONE    200
_TLM_CHECKSUM_
td_vcs1_plate    NONE    200
_TLM_CHECKSUM_
level_sensor_read    NONE    1
cal_lamp_read    NONE    200
_TLM_CHECKSUM_
heater_300mk_read    NONE    1
thermistor_1    NONE    1
thermistor_2    NONE    1
thermistor_3    NONE    1
thermistor_4    NONE    1
thermistor_5    NONE    1
thermistor_6    NONE    1
thermistor_7    NONE    1
thermistor_8    NONE    1
thermistor_9    NONE    1
thermistor_10    NONE    1
thermistor_11    NONE    1
thermistor_12    NONE    1
thermistor_13    NONE    1
thermistor_14    NONE    1
thermistor_15    NONE    1
thermistor_16    NONE    1
thermistor_17    NONE    1
thermistor_18    NONE    1
thermistor_19    NONE    1
thermistor_20    NONE    1
thermistor_21    NONE    1
thermistor_22    NONE    1
thermistor_23    NONE    1
thermistor_24    NONE    1
thermistor_25    NONE    1
thermistor_26    NONE    1
thermistor_27    NONE    1
thermistor_28    NONE    1
thermistor_29    NONE    1
thermistor_30    NONE    1
thermistor_31    NONE    1
thermistor_32    NONE    1
thermistor_33    NONE    1
thermistor_34    NONE    1
thermistor_35    NONE    1
thermistor_36    NONE    1
thermistor_37    NONE    1
thermistor_38    NONE    1
thermistor_39    NONE    1
thermistor_40    NONE    1
thermistor_41    NONE    1
thermistor_42    NONE    1
thermistor_43    NONE    1
thermistor_44    NONE    1
thermistor_45    NONE    1
thermistor_46    NONE    1
thermistor_47    NONE    1
thermistor_48    NONE    1
thermistor_49    NONE    1
thermistor_50    NONE    1
thermistor_51    NONE    1
thermistor_52    NONE    1
thermistor_53    NONE    1
thermistor_54    NONE    1
thermistor_55    NONE    1
thermistor_56    NONE    1
thermistor_57    NONE    1
thermistor_58    NONE    1
thermistor_59    NONE    1
thermistor_60    NONE    1
thermistor_61    NONE    1
thermistor_62    NONE    1
thermistor_63    NONE    1
thermistor_64    NONE    1
thermistor_65    NONE    1
thermistor_66    NONE    1
thermistor_67    NONE    1
thermistor_68    NONE    1
thermistor_69    NONE    1
thermistor_70    NONE    1
thermistor_71    NONE    1
thermistor_72    NONE    1
thermistor_73    NONE    1
thermistor_74    NONE    1
current_eth_switch    NONE    1
current_fc1    NONE    1
current_xsc0    NONE    1
current_fc2    NONE    1
current_xsc1    NONE    1
current_ele_mot    NONE    1
current_pivot    NONE    1
current_rw_mot    NONE    1
current_hd_pv    NONE    1
current_gyros    NONE    1
current_data_transmit    NONE    1
clin_of_x    NONE    1
clin_of_y    NONE    1
clin_if_x    NONE    1
clin_if_y    NONE    1
clin_of_t    NONE    1
clin_if_t    NONE    1
status_charcoal_heater    NONE    1
status_250_LNA    NONE    1
status_1K_heater    NONE    1
status_charcoal_hs    NONE    1
status_500_LNA    NONE    1
status_350_LNA    NONE    1
status_300mk_heater    NONE    1
status_cal_lamp    NONE    1
x_mag1_n    NONE    100
_TLM_CHECKSUM_
y_mag1_n    NONE    100
_TLM_CHECKSUM_
z_mag1_n    NONE    100
_TLM_CHECKSUM_
x_mag2_s    NONE    100
_TLM_CHECKSUM_
y_mag2_s    NONE    100
_TLM_CHECKSUM_
z_mag2_s    NONE    100
_TLM_CHECKSUM_
pos_lock    NONE    5
state_lock    NONE    5
pot_lock    NONE    5
pin_in_lock    NONE    5
mc_rw_vel    NONE    100
_TLM_CHECKSUM_
mc_el_motor_pos    NONE    100
_TLM_CHECKSUM_
mc_piv_pos    NONE    100
