#
# Linklist "shutter.ll" Format File
# Auto-generated by linklist
#
# Serial=c4bafaa2
# Blk Size=34
# Frames per file=900
#
LL_NO_AUTO_CHECKSUM

pos_shutter    NONE    5
steps_shutter    NONE    5
steps_slow_shutter    NONE    5
