#
# Linklist "steppers.ll" Format File
# Auto-generated by linklist
#
# Serial=698763b8
# Blk Size=44
# Frames per file=900
#
LL_NO_AUTO_CHECKSUM

status_actbus    NONE    5
pos_0_act    NONE    5
pos_1_act    NONE    5
pos_2_act    NONE    5
