#
# Linklist "test2.ll" Format File
# Auto-generated by linklist
#
# Serial=a8d108fa
# Blk Size=8976
# Frames per file=900
#
LL_NO_AUTO_CHECKSUM

status_mcc    NONE    1
mcp_1hz_framecount    NONE    1
mcp_5hz_framecount    NONE    5
mcp_100hz_framecount    NONE    100
_TLM_CHECKSUM_
mcp_200hz_framecount    NONE    200
_TLM_CHECKSUM_
mcp_244hz_framecount    NONE    244
_TLM_CHECKSUM_
mcp_488hz_framecount    NONE    488
_TLM_CHECKSUM_
ifyaw_1_gy    NONE    200
_TLM_CHECKSUM_
ifyaw_2_gy    NONE    200
_TLM_CHECKSUM_
ifel_1_gy    NONE    200
_TLM_CHECKSUM_
ifel_2_gy    NONE    200
_TLM_CHECKSUM_
ifroll_1_gy    NONE    200
_TLM_CHECKSUM_
ifroll_2_gy    NONE    200
