#
# Linklist "test.ll" Format File
# Auto-generated by linklist
#
# Serial=1cc2c2a6
# Blk Size=7135
# Frames per file=900
#
LL_NO_AUTO_CHECKSUM

mcp_1hz_framecount    NONE    1
mcp_5hz_framecount    NONE    5
mcp_100hz_framecount    NONE    100
_TLM_CHECKSUM_
mcp_200hz_framecount    NONE    200
_TLM_CHECKSUM_
mcp_244hz_framecount    NONE    244
_TLM_CHECKSUM_
_TLM_CHECKSUM_
test_values    NONE    20
heater_status_write    NONE    1
heater_status_read    NONE    1
cycle_state    NONE    1
_TLM_CHECKSUM_
stage_chopper    NONE    10
read_dio    NONE    1
tr_fpa_1k    NONE    1
tr_250_fpa    NONE    1
tr_1k_plate    NONE    1
_TLM_CHECKSUM_
tr_350_fpa    NONE    1
tr_he3_fridge    NONE    1
tr_500_fpa    NONE    1
rox_bias    NONE    1
status_mcc    NONE    1
stage_chopper    FIXED_PT_16BIT    10
time    FIXED_PT_32BIT    1
_TLM_CHECKSUM_
ifyaw_1_gy    NONE    200
_TLM_CHECKSUM_
ifyaw_2_gy    NONE    200
_TLM_CHECKSUM_
ifroll_1_gy    NONE    200
_TLM_CHECKSUM_
ifroll_2_gy    NONE    200
_TLM_CHECKSUM_
ifel_1_gy    NONE    200
_TLM_CHECKSUM_
ifel_2_gy    NONE    200
