#
# Linklist "test_files.ll" Format File
# Auto-generated by linklist
#
# Serial=9f742229
# Blk Size=12564
# Frames per file=900
#
LL_NO_AUTO_CHECKSUM

mcp_1hz_framecount    NONE    1
mcp_5hz_framecount    NONE    5
mcp_100hz_framecount    NONE    100
_TLM_CHECKSUM_
mcp_200hz_framecount    NONE    200
_TLM_CHECKSUM_
mcp_244hz_framecount    NONE    244
_TLM_CHECKSUM_
ifyaw_1_gy    NONE    200
_TLM_CHECKSUM_
ifyaw_2_gy    NONE    200
_TLM_CHECKSUM_
file_block    B    8750
