#########################################################
# The rule for globally doing stuff to svn repositories
#

THISREPO=$(shell basename `pwd`)
up update ci commit:
	( cd .. && svn $@ $(THISREPO) $(REMOTEPROJ) )

.PHONY: up update ci commit
