#!/bin/sh
module="simbbc_pci"
device="bbcpci"
bipdev="bbc_bi0"

mode="666"

case "$1" in
  start)
	modprobe simbbc_pci || exit 1
  	chmod ${mode} /dev/${device}
	ln -s /dev/null /dev/${bipdev}	
  ;;

  stop) 
	modprobe -r simbbc_pci
	rm -f /dev/${device}
	rm -f /dev/${bipdev}
  ;;
  restart)
	/etc/init.d/simbbc stop
	/etc/init.d/simbbc start
  ;;
  
  *)
    echo "Usage: /etc/init.d/simbbc {start|stop|restart}"
    exit 1
    ;;
	

esac

exit 0
